### ISSUE TITLE
Crash with stack trace on hairy TMP

### ISSUE THREAD

**Issue by rollbear** [andreasfertig/cppinsights#101]
Sorry for not being able to reduce [this](https://cppinsights.io/lnk?code=I2luY2x1ZGUgPHV0aWxpdHk+CiNpbmNsdWRlIDx0eXBlX3RyYWl0cz4KCnRlbXBsYXRlIDx0eXBlbmFtZSBULCBUIHY+CnN0cnVjdCB0eXBlZF9jb25zdGFudAp7CiAgdXNpbmcgdHlwZSA9IFQ7CiAgc3RhdGljIGNvbnN0ZXhwciBUIHZhbHVle3Z9OwogIGNvbnN0ZXhwciBvcGVyYXRvciB0eXBlKCkgY29uc3QgeyByZXR1cm4gdjt9Cn07Cgp0ZW1wbGF0ZTxhdXRvIFY+CnVzaW5nIGNvbnN0YW50ID0gdHlwZWRfY29uc3RhbnQ8c3RkOjpyZW1vdmVfY3ZfdDxkZWNsdHlwZShWKT4sIFY+OwoKdGVtcGxhdGU8YXV0byBWPgppbmxpbmUgY29uc3RleHByIGF1dG8gY29uc3RhbnRfdiA9IGNvbnN0YW50PFY+e307Cgp0ZW1wbGF0ZSA8dHlwZW5hbWUgVDEsIFQxIHYxLCB0eXBlbmFtZSBUMiwgVDIgdjI+CmNvbnN0ZXhwciBjb25zdGFudDwodjErdjIpPiBvcGVyYXRvcisodHlwZWRfY29uc3RhbnQ8VDEsdjE+LHR5cGVkX2NvbnN0YW50PFQyLHYyPikgeyByZXR1cm4ge307fQp0ZW1wbGF0ZSA8dHlwZW5hbWUgVDEsIFQxIHYxLCB0eXBlbmFtZSBUMiwgVDIgdjI+CmNvbnN0ZXhwciBjb25zdGFudDwodjEtdjIpPiBvcGVyYXRvci0odHlwZWRfY29uc3RhbnQ8VDEsdjE+LHR5cGVkX2NvbnN0YW50PFQyLHYyPikgeyByZXR1cm4ge307fQp0ZW1wbGF0ZSA8dHlwZW5hbWUgVDEsIFQxIHYxLCB0eXBlbmFtZSBUMiwgVDIgdjI+CmNvbnN0ZXhwciBjb25zdGFudDwodjEvdjIpPiBvcGVyYXRvci8odHlwZWRfY29uc3RhbnQ8VDEsdjE+LHR5cGVkX2NvbnN0YW50PFQyLHYyPikgeyByZXR1cm4ge307fQp0ZW1wbGF0ZSA8dHlwZW5hbWUgVDEsIFQxIHYxLCB0eXBlbmFtZSBUMiwgVDIgdjI+CmNvbnN0ZXhwciBjb25zdGFudDwodjEqdjIpPiBvcGVyYXRvcioodHlwZWRfY29uc3RhbnQ8VDEsdjE+LHR5cGVkX2NvbnN0YW50PFQyLHYyPikgeyByZXR1cm4ge307fQp0ZW1wbGF0ZSA8dHlwZW5hbWUgVDEsIFQxIHYxLCB0eXBlbmFtZSBUMiwgVDIgdjI+CmNvbnN0ZXhwciBjb25zdGFudDwodjEldjIpPiBvcGVyYXRvciUodHlwZWRfY29uc3RhbnQ8VDEsdjE+LHR5cGVkX2NvbnN0YW50PFQyLHYyPikgeyByZXR1cm4ge307fQp0ZW1wbGF0ZSA8dHlwZW5hbWUgVDEsIFQxIHYxLCB0eXBlbmFtZSBUMiwgVDIgdjI+CmNvbnN0ZXhwciBjb25zdGFudDwodjE9PXYyKT4gb3BlcmF0b3I9PSh0eXBlZF9jb25zdGFudDxUMSx2MT4sdHlwZWRfY29uc3RhbnQ8VDIsdjI+KSB7IHJldHVybiB7fTt9CnRlbXBsYXRlIDx0eXBlbmFtZSBUMSwgVDEgdjEsIHR5cGVuYW1lIFQyLCBUMiB2Mj4KY29uc3RleHByIGNvbnN0YW50PCh2MSE9djIpPiBvcGVyYXRvciE9KHR5cGVkX2NvbnN0YW50PFQxLHYxPix0eXBlZF9jb25zdGFudDxUMix2Mj4pIHsgcmV0dXJuIHt9O30KdGVtcGxhdGUgPHR5cGVuYW1lIFQxLCBUMSB2MSwgdHlwZW5hbWUgVDIsIFQyIHYyPgpjb25zdGV4cHIgY29uc3RhbnQ8KHYxPHYyKT4gb3BlcmF0b3I8KHR5cGVkX2NvbnN0YW50PFQxLHYxPix0eXBlZF9jb25zdGFudDxUMix2Mj4pIHsgcmV0dXJuIHt9O30KdGVtcGxhdGUgPHR5cGVuYW1lIFQxLCBUMSB2MSwgdHlwZW5hbWUgVDIsIFQyIHYyPgpjb25zdGV4cHIgY29uc3RhbnQ8KHYxPD12Mik+IG9wZXJhdG9yPD0odHlwZWRfY29uc3RhbnQ8VDEsdjE+LHR5cGVkX2NvbnN0YW50PFQyLHYyPikgeyByZXR1cm4ge307fQp0ZW1wbGF0ZSA8dHlwZW5hbWUgVDEsIFQxIHYxLCB0eXBlbmFtZSBUMiwgVDIgdjI+CmNvbnN0ZXhwciBjb25zdGFudDwodjE+djIpPiBvcGVyYXRvcj4odHlwZWRfY29uc3RhbnQ8VDEsdjE+LHR5cGVkX2NvbnN0YW50PFQyLHYyPikgeyByZXR1cm4ge307fQp0ZW1wbGF0ZSA8dHlwZW5hbWUgVDEsIFQxIHYxLCB0eXBlbmFtZSBUMiwgVDIgdjI+CmNvbnN0ZXhwciBjb25zdGFudDwodjE+PXYyKT4gb3BlcmF0b3I+PSh0eXBlZF9jb25zdGFudDxUMSx2MT4sdHlwZWRfY29uc3RhbnQ8VDIsdjI+KSB7IHJldHVybiB7fTt9CnRlbXBsYXRlIDx0eXBlbmFtZSBUMSwgVDEgdjEsIHR5cGVuYW1lIFQyLCBUMiB2Mj4KY29uc3RleHByIGNvbnN0YW50PCh2MXx2Mik+IG9wZXJhdG9yfCh0eXBlZF9jb25zdGFudDxUMSx2MT4sdHlwZWRfY29uc3RhbnQ8VDIsdjI+KSB7IHJldHVybiB7fTt9CnRlbXBsYXRlIDx0eXBlbmFtZSBUMSwgVDEgdjEsIHR5cGVuYW1lIFQyLCBUMiB2Mj4KY29uc3RleHByIGNvbnN0YW50PCh2MSZ2Mik+IG9wZXJhdG9yJih0eXBlZF9jb25zdGFudDxUMSx2MT4sdHlwZWRfY29uc3RhbnQ8VDIsdjI+KSB7IHJldHVybiB7fTt9CnRlbXBsYXRlIDx0eXBlbmFtZSBUMSwgVDEgdjEsIHR5cGVuYW1lIFQyLCBUMiB2Mj4KY29uc3RleHByIGNvbnN0YW50PCh2MV52Mik+IG9wZXJhdG9yXih0eXBlZF9jb25zdGFudDxUMSx2MT4sdHlwZWRfY29uc3RhbnQ8VDIsdjI+KSB7IHJldHVybiB7fTt9CnRlbXBsYXRlIDx0eXBlbmFtZSBUMSwgVDEgdjEsIHR5cGVuYW1lIFQyLCBUMiB2Mj4KY29uc3RleHByIGNvbnN0YW50PCh2MSYmdjIpPiBvcGVyYXRvciYmKHR5cGVkX2NvbnN0YW50PFQxLHYxPix0eXBlZF9jb25zdGFudDxUMix2Mj4pIHsgcmV0dXJuIHt9O30KdGVtcGxhdGUgPHR5cGVuYW1lIFQxLCBUMSB2MSwgdHlwZW5hbWUgVDIsIFQyIHYyPgpjb25zdGV4cHIgY29uc3RhbnQ8KHYxfHx2Mik+IG9wZXJhdG9yfHwodHlwZWRfY29uc3RhbnQ8VDEsdjE+LHR5cGVkX2NvbnN0YW50PFQyLHYyPikgeyByZXR1cm4ge307fQoKdGVtcGxhdGUgPHR5cGVuYW1lIFQxLCBhdXRvIHYxPgpjb25zdGV4cHIgY29uc3RhbnQ8IXYxPiBvcGVyYXRvciEodHlwZWRfY29uc3RhbnQ8VDEsdjE+KSB7IHJldHVybiB7fTt9CnRlbXBsYXRlIDx0eXBlbmFtZSBUMSwgVDEgdjE+CmNvbnN0ZXhwciBjb25zdGFudDwofnYxKT4gb3BlcmF0b3J+KHR5cGVkX2NvbnN0YW50PFQxLHYxPikgeyByZXR1cm4ge307fQoKCm5hbWVzcGFjZSBkZXRhaWwKewoKdGVtcGxhdGUgPHR5cGVuYW1lIFQsIHR5cGVuYW1lID0gdm9pZD4Kc3RydWN0IGhhc19jb250aW51YXRpb24KewogIHN0YXRpYyBjb25zdGV4cHIgYm9vbCB2YWx1ZSA9IGZhbHNlOwp9OwoKdGVtcGxhdGUgPHR5cGVuYW1lIFQ+CnN0cnVjdCBoYXNfY29udGludWF0aW9uPFQsIHN0ZDo6dm9pZF90PHR5cGVuYW1lIFQ6OmNvbnRpbnVhdGlvbj4+CnsKICBzdGF0aWMgY29uc3RleHByIGJvb2wgdmFsdWUgPSB0cnVlOwp9OwoKdGVtcGxhdGUgPHR5cGVuYW1lIFQsIGJvb2wgPSBoYXNfY29udGludWF0aW9uPFQ+Ojp2YWx1ZT4Kc3RydWN0IHRvXwp7CiAgdXNpbmcgdHlwZSA9IFQ7Cn07Cgp0ZW1wbGF0ZSA8dHlwZW5hbWUgVD4Kc3RydWN0IHRvXzxULCB0cnVlPgp7CiAgdXNpbmcgdHlwZSA9IHR5cGVuYW1lIFQ6OnRlbXBsYXRlIHRvPHR5cGVuYW1lIFQ6OmNvbnRpbnVhdGlvbj47Cn07CgoKdGVtcGxhdGUgPHR5cGVuYW1lIFQ+CnVzaW5nIHRvID0gdHlwZW5hbWUgdG9fPFQ+Ojp0eXBlOwoKfQoKdGVtcGxhdGU8dHlwZW5hbWUuLi4+CnN0cnVjdCBsaXN0IHt9OwoKdGVtcGxhdGU8dGVtcGxhdGU8dHlwZW5hbWUgLi4uPiBjbGFzcyBDPgpzdHJ1Y3QgbWFrZSB7CiAgdGVtcGxhdGU8dHlwZW5hbWUgLi4uIFRzPgogIHVzaW5nIHJlc3VsdCA9IEM8VHMuLi4+Owp9OwoKdGVtcGxhdGUgPHR5cGVuYW1lIEYsIHR5cGVuYW1lIFQ+CnVzaW5nIGFwcGx5X29uZSA9IHR5cGVuYW1lIEY6OnRlbXBsYXRlIHJlc3VsdDxUPjsKCnN0cnVjdCBpZGVudGl0eSB7CiAgdGVtcGxhdGU8dHlwZW5hbWUgVD4KICB1c2luZyByZXN1bHQgPSBUOwp9OwoKdGVtcGxhdGUgPHRlbXBsYXRlIDx0eXBlbmFtZSAuLi4+IGNsYXNzIFQsIHR5cGVuYW1lIC4uLiBUcz4Kc3RydWN0IGJpbmRfZnJvbnQgewogIHRlbXBsYXRlIDx0eXBlbmFtZSAuLi4gVnM+CiAgc3RydWN0IGhlbHBlciB7CiAgICB1c2luZyB0eXBlID0gVDxUcy4uLiwgVnMuLi4+OwogIH07CiAgdGVtcGxhdGUgPHR5cGVuYW1lIC4uLiBWcz4KICB1c2luZyByZXN1bHQgPSB0eXBlbmFtZSBoZWxwZXI8VnMuLi4+Ojp0eXBlOwp9OwoKdGVtcGxhdGU8dGVtcGxhdGUgPHR5cGVuYW1lLi4uPiBjbGFzcyBUPgpzdHJ1Y3QgZnJvbV90eXBlIHsKICB1c2luZyBjb250aW51YXRpb24gPSBpZGVudGl0eTsKICB0ZW1wbGF0ZSA8dHlwZW5hbWUgQyA9IGNvbnRpbnVhdGlvbj4KICBzdHJ1Y3QgdG8gewogICAgdXNpbmcgVE8gPSBkZXRhaWw6OnRvPEM+OwogICAgdGVtcGxhdGU8dHlwZW5hbWUgLi4uIFZzPgogICAgc3RydWN0IGhlbHBlciB7CiAgICAgIHVzaW5nIHR5cGUgPSBhcHBseV9vbmU8VE8sIHR5cGVuYW1lIFQ8VnMuLi4+Ojp0eXBlPjsKICAgIH07CiAgICB0ZW1wbGF0ZTx0eXBlbmFtZSAuLi4gVnM+CiAgICB1c2luZyByZXN1bHQgPSB0eXBlbmFtZSBoZWxwZXI8VnMuLi4+Ojp0eXBlOwogIH07Cn07Cgp0ZW1wbGF0ZSA8dGVtcGxhdGUgPHR5cGVuYW1lIC4uLj4gY2xhc3MgVD4Kc3RydWN0IGZyb21fdmFsdWUKewogIHVzaW5nIGNvbnRpbnVhdGlvbiA9IGlkZW50aXR5OwogIHRlbXBsYXRlIDx0eXBlbmFtZSBDID0gY29udGludWF0aW9uPgogIHN0cnVjdCB0byB7CiAgICB1c2luZyBUTyA9IGRldGFpbDo6dG88Qz47CiAgICB0ZW1wbGF0ZTx0eXBlbmFtZSAuLi4gVnM+CiAgICB1c2luZyByZXN1bHQgPSBhcHBseV9vbmU8VE8sIGNvbnN0YW50PFQ8VnMuLi4+Ojp2YWx1ZT4+OwogIH07Cn07CgoKdGVtcGxhdGUgPHR5cGVuYW1lIC4uLj4Kc3RydWN0IGNvbXBvc2U7Cgp0ZW1wbGF0ZSA8PgpzdHJ1Y3QgY29tcG9zZTw+CnsKICB1c2luZyBjb250aW51YXRpb24gPSBpZGVudGl0eTsKICB0ZW1wbGF0ZSA8dHlwZW5hbWUgQyA9IGNvbnRpbnVhdGlvbj4KICBzdHJ1Y3QgdG8KICB7CiAgICB1c2luZyBUID0gZGV0YWlsOjp0bzxDPjsKICAgIHRlbXBsYXRlIDx0eXBlbmFtZSAuLi4gVHM+CiAgICB1c2luZyByZXN1bHQgPSB0eXBlbmFtZSBUOjp0ZW1wbGF0ZSByZXN1bHQ8VHMuLi4+OwogIH07Cn07Cgp0ZW1wbGF0ZSA8dHlwZW5hbWUgRiwgdHlwZW5hbWUgLi4uIEZzPgpzdHJ1Y3QgY29tcG9zZTxGLCBGcy4uLj4KewogIHVzaW5nIGNvbnRpbnVhdGlvbiA9IHR5cGVuYW1lIEY6OmNvbnRpbnVhdGlvbjsKICB0ZW1wbGF0ZSA8dHlwZW5hbWUgQyA9IGNvbnRpbnVhdGlvbj4KICBzdHJ1Y3QgdG8KICB7CiAgICB0ZW1wbGF0ZSA8dHlwZW5hbWUgLi4uIFRzPgogICAgdXNpbmcgcmVzdWx0ID0gdHlwZW5hbWUgY29tcG9zZTxGcy4uLj46OnRlbXBsYXRlIHRvPHR5cGVuYW1lIEY6OnRlbXBsYXRlIHRvPEM+Pjo6dGVtcGxhdGUgcmVzdWx0PFRzLi4uPjsKICB9Owp9OwoKc3RydWN0IGFkZF9jb25zdAp7CiAgdXNpbmcgY29udGludWF0aW9uID0gaWRlbnRpdHk7CiAgdGVtcGxhdGUgPHR5cGVuYW1lIEMgPSBjb250aW51YXRpb24+CiAgc3RydWN0IHRvCiAgewogICAgdGVtcGxhdGUgPHR5cGVuYW1lIFQ+CiAgICBzdHJ1Y3QgaW5uZXIgewogICAgICB1c2luZyB0eXBlID0gYXBwbHlfb25lPEMsIGNvbnN0IFQ+OwogICAgfTsKICAgIHRlbXBsYXRlIDx0eXBlbmFtZSAuLi5UPgogICAgdXNpbmcgcmVzdWx0ID0gdHlwZW5hbWUgaW5uZXI8VC4uLj46OnR5cGU7CiAgfTsKfTsKCnN0cnVjdCBhZGRfcG9pbnRlcgp7CiAgdXNpbmcgY29udGludWF0aW9uID0gaWRlbnRpdHk7CiAgdGVtcGxhdGUgPHR5cGVuYW1lIEMgPSBjb250aW51YXRpb24+CiAgc3RydWN0IHRvCiAgewogICAgdGVtcGxhdGUgPHR5cGVuYW1lIFQ+CiAgICBzdHJ1Y3QgaW5uZXIgewogICAgICB1c2luZyB0eXBlID0gYXBwbHlfb25lPEMsIFQqPjsKICAgIH07CiAgICB0ZW1wbGF0ZSA8dHlwZW5hbWUgLi4uVD4KICAgIHVzaW5nIHJlc3VsdCA9IHR5cGVuYW1lIGlubmVyPFQuLi4+Ojp0eXBlOwogIH07Cn07Cgp0ZW1wbGF0ZSA8dHlwZW5hbWUgVD4Kc3RydWN0IHdyYXBwZWQge307CgpzdHJ1Y3Qgd3JhcAp7CiAgdGVtcGxhdGUgPHR5cGVuYW1lIFQ+CiAgdXNpbmcgcmVzdWx0ID0gd3JhcHBlZDxUPjsKfTsKCnRlbXBsYXRlIDx0eXBlbmFtZSBGLCB0eXBlbmFtZSAuLi4gVHM+CnVzaW5nIGFwcGx5ID0gdHlwZW5hbWUgRjo6dGVtcGxhdGUgdG88Pjo6dGVtcGxhdGUgcmVzdWx0PFRzLi4uPjsKdGVtcGxhdGUgPHR5cGVuYW1lIEYsIHR5cGVuYW1lIEMsIHR5cGVuYW1lIC4uLiBUcz4KdXNpbmcgYXBwbHlfdG8gPSB0eXBlbmFtZSBGOjp0ZW1wbGF0ZSB0bzxDPjo6dGVtcGxhdGUgcmVzdWx0PFRzLi4uPjsKCnN0YXRpY19hc3NlcnQoc3RkOjppc19zYW1lX3Y8YXBwbHk8Y29tcG9zZTxhZGRfcG9pbnRlcj4sIGludD4sIGludCo+KTsKc3RhdGljX2Fzc2VydChzdGQ6OmlzX3NhbWVfdjxhcHBseTxjb21wb3NlPGFkZF9wb2ludGVyLCBhZGRfY29uc3Q+LGludD4sIGNvbnN0IGludCo+KTsKc3RhdGljX2Fzc2VydChzdGQ6OmlzX3NhbWVfdjxhcHBseTxjb21wb3NlPGFkZF9jb25zdCwgYWRkX3BvaW50ZXI+LGludD4sIGludCpjb25zdD4pOwpzdGF0aWNfYXNzZXJ0KHN0ZDo6aXNfc2FtZV92PGFwcGx5X3RvPGNvbXBvc2U8YWRkX3BvaW50ZXI+LCB3cmFwLCBpbnQ+LCB3cmFwcGVkPGludCo+Pik7CnN0YXRpY19hc3NlcnQoc3RkOjppc19zYW1lX3Y8YXBwbHlfdG88Y29tcG9zZTxhZGRfcG9pbnRlciwgYWRkX2NvbnN0Pix3cmFwLCBpbnQ+LCB3cmFwcGVkPGNvbnN0IGludCo+Pik7Cg==&rev=1.0) one.

Any attempt at peeling off a layer seems to make it work. Clang itself, and gcc too, handles it fine.

**Comment by andreasfertig** [comment]
Sorry, I'm testing stale bot and it does exactly the opposite of what I want. This issue will remain open.
