### ISSUE TITLE
unexpected behavior when explicitly instantiating a template

### ISSUE THREAD

**Issue by matkatmusic** [andreasfertig/cppinsights#123]
I'm not sure what the expected behavior is, but this snippet shows no template instantiation code being generated: 

```
template<typename T>
struct Person
{
	int age, heightInInches;
	T distanceTraveled = T(); //default value
	float hairLength, GPA;
	unsigned int SATScore;

	T run(T speed, bool startWithLeftFoot);
};

template<typename T>
T Person<T>::run(T speed, bool left )
{
	return speed + (left ? 1 : 0);
}

template struct Person<int>;

int main()
{
	Person<int> f;
	auto x = f.run(2, true);
}
```
If you comment out the `template struct Person<int>;` it generates the expected template code.
Any ideas on why this happens? 

I was expecting to this:
```
/* First instantiated from: insights.cpp:22 */
#ifdef INSIGHTS_USE_TEMPLATE
template<>
struct Person<int>
{
  int age;
  int heightInInches;
  int distanceTraveled = int();
  float hairLength;
  float GPA;
  unsigned int SATScore;
  int run(int speed, bool left)
  {
    return speed + (left ? 1 : 0);
  }
  
  // inline Person() noexcept = default;
  // inline constexpr Person(const Person<int> &) = default;
  // inline constexpr Person(Person<int> &&) = default;
};
```

**Comment by andreasfertig** [comment]
Hello @matkatmusic,

you are totally right. I have trouble with the AST matchers. A quick fix broke existing tests. I need to take a closer look and how to handle this.

Andreas

**Comment by andreasfertig** [comment]
All right, I understood it. In the progress I found a second issue. Thanks for reporting the bug!

**Comment by matkatmusic** [comment]
This UB still exists.  This issue should remain open until cppinsights displays the correct result. 

https://cppinsights.io/lnk?code=dGVtcGxhdGU8dHlwZW5hbWUgVD4Kc3RydWN0IFBlcnNvbgp7CglpbnQgYWdlLCBoZWlnaHRJbkluY2hlczsKCVQgZGlzdGFuY2VUcmF2ZWxlZCA9IFQoKTsgLy9kZWZhdWx0IHZhbHVlCglmbG9hdCBoYWlyTGVuZ3RoLCBHUEE7Cgl1bnNpZ25lZCBpbnQgU0FUU2NvcmU7CgoJVCBydW4oVCBzcGVlZCwgYm9vbCBzdGFydFdpdGhMZWZ0Rm9vdCk7Cn07Cgp0ZW1wbGF0ZTx0eXBlbmFtZSBUPgpUIFBlcnNvbjxUPjo6cnVuKFQgc3BlZWQsIGJvb2wgbGVmdCApCnsKCXJldHVybiBzcGVlZCArIChsZWZ0ID8gMSA6IDApOwp9Cgp0ZW1wbGF0ZSBzdHJ1Y3QgUGVyc29uPGludD47CgppbnQgbWFpbigpCnsKCVBlcnNvbjxpbnQ+IGY7CglhdXRvIHggPSBmLnJ1bigyLCB0cnVlKTsKfQ==&std=cpp17&rev=1.0

**Comment by andreasfertig** [comment]
Hello @matkatmusic,

can you be more specific? For what I see the output matches what you expect according to your initial post (and what I agree that it is correct). Maybe you checked to soon? After it appears as closed here it takes some time to do the build and upload it to the server.

**Comment by matkatmusic** [comment]
My fault, it is working as expected.  I must have checked too soon after you fixed it.
