### ISSUE TITLE
Generic lambdas are not supported

### ISSUE THREAD

**Issue by languagelawyer** [andreasfertig/cppinsights#127]
`auto f = [](auto) {};` is transformed into
```c++

class __lambda_1_10
{
  
};

__lambda_1_10 f = __lambda_1_10{};

```
No templated `operator()` or anything at all. https://godbolt.org/z/MHGiCl

**Comment by andreasfertig** [comment]
Hello @languagelawyer,

it depends a bit on what you are expecting. A slight change does show the operator:

```C++
auto f = [](auto) {};

int main()
{
  f(1);
}
```

In my case it is instantiated. Is your request about showing the templated declaration?

**Comment by languagelawyer** [comment]
> Is your request about showing the templated declaration?

Yes.

**Comment by andreasfertig** [comment]
I thought so. Currently, C++ Insights leaves templates declarations untouched. That's why it does not generated the template declaration in this case. I'm working on that, but it will take time.
