### ISSUE TITLE
Ellipsis missing from template instatiation

### ISSUE THREAD

**Issue by knatten** [andreasfertig/cppinsights#128]
The instantiation from this code:
```cpp
template<typename T>
void foo(T, ...) {}

int main(){
   foo(1, 2.);
}
```

Looks like this:
```cpp
template<>
void foo<int>(int)
{
}
```

I think the signature should rather be `void foo<int>(int, ...)`.

Try it on [CppInsights.io](https://cppinsights.io/lnk?code=dGVtcGxhdGU8dHlwZW5hbWUgVD4Kdm9pZCBmb28oVCwgLi4uKSB7fQoKaW50IG1haW4oKXsKICAgZm9vKDEsIDIuKTsKfQ==&std=cpp17&rev=1.0)

**Comment by andreasfertig** [comment]
Hello @knatten,

thanks for reporting that. It is indeed incorrect. A fix is on its way.

Andreas

**Comment by knatten** [comment]
That was quick! <3
