### ISSUE TITLE
the generated URLs are to long in web version (for convenience)

### ISSUE THREAD

**Issue by simonrenger** [andreasfertig/cppinsights#133]
Hello,

the domains which the tool generates are way too long. Is there the plan to change it like on compiler explorer does it? 

comparison:
```
https://cppinsights.io/lnk?code=I2luY2x1ZGUgPHZlY3Rvcj4KI2luY2x1ZGUgPGNzdGRpbz4KCmludCBtYWluKCkKewogIHN0ZDo6dmVjdG9yPGludD4gdGVzdHsxLDIsMyw0LDV9OwogIAogIGZvcihhdXRvIGkgPSAwO2kgPCB0ZXN0LnNpemUoKTsrK2kpCiAgICArK3Rlc3RbaV07CiAKICAgICBjb25zdCBjaGFyIGFyclsxMF17Miw0LDYsOH07CgogICAgZm9yKGNvbnN0IGNoYXImIGMgOiBhcnIpCiAgICB7CiAgICAgIHByaW50ZigiYz0lY1xuIiwgYyk7CiAgICB9Cn0=&std=cpp17&rev=1.0
```
vs
```
https://gcc.godbolt.org/z/kv7yra
```

**Comment by andreasfertig** [comment]
Hello @simonrenger,

yes there is a plan for that. See [patreon](https://www.patreon.com/posts/happy-new-year-23819519).
But it will take some time. Especially because I do not like to store confidential content. The idea is to create something like an open database. You can great short links, but everybody can browse that database and see them. It also fits into the teaching concept of C++ Insights, other may learn from your links.

Andreas

**Comment by matkatmusic** [comment]
Could you do something like pastebin, how recent links are public unless you make them private?   the ability to delete your snippets could require a paid membership, maybe...

it's been done on a bunch of sites, maybe see how they do it.  Wandbox's implementation is open-source.  their shared URLs are pretty short.  https://github.com/melpon/wandbox

**Comment by simonrenger** [comment]
@andreasfertig if you need help with creating something like this I could help :) especially what @matkatmusic  suggested.

**Comment by andreasfertig** [comment]
Hello @simonrenger,

thank you, that would be great!

What I have in mind so far is to store the links in a sqlite database. As the primary intend of C++ Insights is teaching and others can learn from your code snippets, all links should be publicly available. The idea is to provide a dedicated page which lists all the short-links. Only the full links are private. Maybe store a "used" flag to check, if a link was used at least one time to be able to do some house-keeping.

If you are skilled at web-dev I would appreciate some JavaScript unit tests. This becomes more important with more JavaScript code. Currently, I'm working on a patch to support #44 and #45. With that I started using karma and jasmine. However, I'm not able to get CodeMirror working in this setup. I will probably push it next weekend, then you can see what I'm talking about.

Andreas

**Comment by andreasfertig** [comment]
Fix with https://github.com/andreasfertig/cppinsights-web/pull/32
