### ISSUE TITLE
redundant(?) double static_cast

### ISSUE THREAD

**Issue by danra** [andreasfertig/cppinsights#134]
The following:
`int a = (int)1.0;`

translates into
`int a = static_cast<int>(static_cast<int>(1.0));`

See https://cppinsights.io/lnk?code=aW50IG1haW4oKQp7CiAgCWludCBhID0gKGludCkxLjA7Cn0=&std=cpp17&rev=1.0

AFAICS there is a redundant `static_cast<int>` here - unless this is what the compiler actually does internally (for some reason?)

**Comment by andreasfertig** [comment]
Hello @danra,

I believe what C++ Insights shows is correct. Have a look here: [https://godbolt.org/z/FC_pXU](https://godbolt.org/z/FC_pXU). It shows the AST output of your example and a second version with the C-Style-Cast. In C++ Insights the second version leads to only one `static_cast`. I assume the compiler does optimize this away in a later stage.

Andreas
