### ISSUE TITLE
missed template instantiation

### ISSUE THREAD

**Issue by leni536** [andreasfertig/cppinsights#143]
Cppinsights.io doesn't show the template instantiation for ```max``` in the following code:

```cpp
#include <string>
#include <utility>

template <typename T, typename Comp>
T& max(T& v1, T& v2, Comp&& comp) {
    return std::forward<Comp>(comp)(v1, v2)
           ? v2
           : v1;
}

void foo() {
    constexpr auto longer = [](auto&& s1, auto&& s2){
        return s1.length() < s2.length();
    };

    const auto s1 = std::string{"foo"};
    const auto s2 = std::string("barr");

    auto l5 = max(s1, s2, longer);
}
```

Note: it would be nice if the website showed version info or commit hash that I could include into the bug report.

**Comment by andreasfertig** [comment]
Hello @leni536,

thank you for reporting that. It is an interesting case. Have a look at [Compiler Explorer](https://godbolt.org/z/_3Nm2s) and the AST output:

```
| `-FunctionDecl <line:5:1, line:9:1> line:5:4 max 'const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > &(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > &, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > &, const (lambda at line:12:29) &)'
|   |-TemplateArgument type 'const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
|   |-TemplateArgument type 'const (lambda at line:12:29) &'
|   |-ParmVarDecl <col:8, col:11> col:11 v1 'const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > &'
|   |-ParmVarDecl <col:15, col:18> col:18 v2 'const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > &'
|   `-ParmVarDecl <col:22, col:29> col:29 comp 'const (lambda at line:12:29) &'
`-FunctionDecl <line:11:1, line:20:1> line:11:6 foo 'void ()'
```

The template instantiation C++ Insights see is the one above. Now, it has no body in the AST! There is a check in the code to skip such functions. Normally, this is the case for functions which are unused. 

I haven't figured out why and how your example leads to that result, but as far as the resulting instantiation has no body C++ Insights can do anything better.

Regarding the commit hash, this is an excellent idea. I'm already working on that including the version of C++ Insights itself and a hash which will be available for the downloads as well. However, it will take some time until it is ready.

Andreas

**Comment by andreasfertig** [comment]
Hello @leni536,

today I pushed a new version of C++ Insights and the website. You can now look up what version of C++ Insights is running at [cppinsights.io](https://cppinsights.io): [https://cppinsights.io/version](https://cppinsights.io/version).

**Comment by andreasfertig** [comment]
Hello @leni536,

I also understood your initial issue. With including, I assume, `string` the code also drags in the `algorithm`header. This header contains already a `max` function-template: [https://en.cppreference.com/w/cpp/algorithm/max](https://en.cppreference.com/w/cpp/algorithm/max). I looks like the one provided in your code was not picked up by overload resolution. With that C++ Insights gives you the correct output :-). If you change the code slightly, to a max with a capital `M` C++ Insights shows you the template instantiation:

```C++
#include <string>
#include <utility>

template <typename T, typename Comp>
T& Max(T& v1, T& v2, Comp&& comp) {
    return std::forward<Comp>(comp)(v1, v2)
           ? v2
           : v1;
}

void foo() {
    constexpr auto longer = [](auto&& s1, auto&& s2){
        return s1.length() < s2.length();
    };

    const auto s1 = std::string{"foo"};
    const auto s2 = std::string("barr");

    auto l5 = Max(s1, s2, longer);
}
```

**Comment by leni536** [comment]
Oh, damn ADL, nice catch :). It showcases an opportunity to somehow show what function gets called  at each call site (with fully qualified name and arguments), maybe in a tooltip when hovered over function (otherwise it would quickly become unreadable).
