### ISSUE TITLE
Feature request: Generate insights for std::accumulate

### ISSUE THREAD

**Issue by siedentop** [andreasfertig/cppinsights#144]
Thank you for this very cool tool! Would it be possible to generate insights for `std::accumulate`? 

Suggested label: Enhancement.

Code:
```c++
#include <cstdio>
#include <numeric>
#include <array>

int main()
{
   std::array<uint8_t, 5> arr{2,4,6,8,10};
   int x = std::accumulate(arr.begin(), arr.end(), 0);
   return 0;
}
```

Link: https://cppinsights.io/lnk?code=I2luY2x1ZGUgPGNzdGRpbz4KI2luY2x1ZGUgPG51bWVyaWM+CiNpbmNsdWRlIDxhcnJheT4KCmludCBtYWluKCkKewogICAgc3RkOjphcnJheTx1aW50OF90LCA1PiBhcnJ7Miw0LDYsOCwxMH07CgogICBpbnQgeCA9IHN0ZDo6YWNjdW11bGF0ZShhcnIuYmVnaW4oKSwgYXJyLmVuZCgpLCAwKTsKICAgcmV0dXJuIDA7Cn0=&std=cpp2a&rev=1.0

**Comment by andreasfertig** [comment]
Hello @siedentop,

thank you, my pleasure!

I'm not sure I understand what you are asking for. Do you want to see the result? The possible loop inside accumulate? In all cases, if it is not in the AST it will be hard to show it.

Andreas

**Comment by siedentop** [comment]
Hi Andreas, 

I would assume that std::accumulate get's unpacked to a simple loop. Doesn't it?

My assumption was that it gets transformed in the same way a range-for loop get's changed to a simple (old-style) loop.

```
   // This get's unwrapped nicely
   uint8_t v = 0;
   for (auto y : arr ) {
      v += y;
   }
```

Maybe my assumption about what the compiler does is wrong and std::accumulate never gets "inlined" to become part of the AST of this translation unit? If so, then please close the ticket, since cppinsights shouldn't / can't show this.

Best regards
Christoph

**Comment by andreasfertig** [comment]
Hello @siedentop,

possibly it gets transformed. However, this is an optimization detail and as far as I know and can see not part of the AST. Hence, I close this issue. Thank you!
