### ISSUE TITLE
Make lifetime extension explicit

### ISSUE THREAD

**Issue by BenFrantzDale** [andreasfertig/cppinsights#156]
Thanks for creating such a cool tool!

It would be great if lifetime extension were made explicit. That is, the GOTW#88 `const&` behavior: https://herbsutter.com/2008/01/01/gotw-88-a-candidate-for-the-most-important-const/

as in
```
struct C { virtual int get() const { return 0; } };
struct D : C { virtual int get() const override { return 1; } };

int foo() {
	const C& c = D();
  	return c.get();
}
```

Right now the above produces
```
...
int foo()
{
  const C & c = static_cast<const C&>(D());
  return c.get();
}
```
which is correct, but the insight I'd like to see would show that after the `return`, `c` is destroyed with `D::~D()`.

I'm not sure how you'd show that in the output, though... Maybe in a comment?

**Comment by andreasfertig** [comment]
Hello @BenFrantzDale,

thank you, my pleasure.
I totally agree, it would be great. However, have a look at this [discussion](http://clang-developers.42468.n3.nabble.com/how-to-see-implicit-calls-in-AST-td4034469.html) on the Clang developers list. Object lifetime is not modeled in the AST. 
I haven't looked into how the static analyzer does it as the comment also suggests. I will do that as soon as I find the time for it. So far assume that it is impossible and will not be part of C++ Insights. But of course, feel free to show me a way.

Andreas
