### ISSUE TITLE
Provide optimization flag?

### ISSUE THREAD

**Issue by BenFrantzDale** [andreasfertig/cppinsights#157]
This may not be feasible, but it would be very interesting if the `-O` flag were available so that, as in godbolt, we could see the effect of optimization on things like loop unrolling and inlining.

**Comment by andreasfertig** [comment]
Hello @BenFrantzDale,

unfortunately it is not how it works. Have a look at this code in [godbolt](https://godbolt.org/z/ldDNIT). It shows the same code with the same compiler version with `-O0` and `-O3`. As you can see in the assembly output the optimization in fact changes the resulting assembly output. However, the AST remains the same. The AST is from the front-end stage, before `-O` flags kick in.
If you know a way to get hands on the optimized AST let me know.

Andreas
