### ISSUE TITLE
artifacts }; remain for N3922 declarations

### ISSUE THREAD

**Issue by stullemitbrot** [andreasfertig/cppinsights#158]
declaration + definition 
`auto x  { 27 };`
yields
```
int x = 27;
 };
```
which is obviously wrong.

**Comment by andreasfertig** [comment]
Hello @stullemitbrot,

thanks for reporting that. I'll have a look at it. Looks like the extracted range is incomplete.

Andreas

**Comment by stullemitbrot** [comment]
Hallo Andreas,

sounds plausible :)
Nevertheless great work, Thanx!

Reinhard
