### ISSUE TITLE
Boby of one-liner ranged-based for discarded

### ISSUE THREAD

**Issue by hrjonashansen** [andreasfertig/cppinsights#161]
The following snippet creates a c-style array and prints the elements one by one. However, the printing part is not included in the output of cppinsights.io.

Snippet:

    #include <iostream>

    int main(int argc, char** argv)
    {
        char arr[10]{2,4,6,8};
        for (auto i : arr)
            std::cout << i << " ";
    }

Output:

    #include <iostream>

    int main(int argc, char ** argv)
    {
      char arr[10] = {2, 4, 6, 8, '\0', '\0', '\0', '\0', '\0', '\0'};
      {
        char (&__range1)[10] = arr;
        char * __begin1 = __range1;
        char * __end1 = __range1 + 10l;
        for(; __begin1 != __end1; ++__begin1) 
        {
          char i = *__begin1;
        }
        
      }
    }

**Comment by andreasfertig** [comment]
Hello @hrjonashansen,

thanks for reporting that! Indeed that statement got lost in the process. A fix is on its way.

Andreas
