### ISSUE TITLE
template lambda not compiling

### ISSUE THREAD

**Issue by kobi-ca** [andreasfertig/cppinsights#176]
Shouldn't this work with 17 or 2a?
```
#include <iostream>
 
int main()
{
	auto foo = []<typename T>(T i) { return 1; };
    foo(3);
    return 0;
}
```

**Comment by kobi-ca** [comment]
getting
```
/home/insights/insights.cpp:7:15: error: expected body of lambda expression
        auto foo = []<typename T>(T i) { return 1; };
                     ^
/home/insights/insights.cpp:7:25: error: expected a qualified name after 'typename'
        auto foo = []<typename T>(T i) { return 1; };
                               ^
2 errors generated.
```

**Comment by andreasfertig** [comment]
Hello @kobi-ca,

you are trying to use [P0428R2](https://wg21.link/P0428) which is a 2a feature. However, it is not implemented in Clang yet (see also [cppreference.com](https://en.cppreference.com/w/cpp/compiler_support)).
I'm already watching the progress, but even if it gets implemented in Clang it will take to the next major release to be available in C++ Insights.
I leave that issue open until it is available.

Andreas

**Comment by kobi-ca** [comment]
got it. thanks for the clarification.
