### ISSUE TITLE
spell out using declaration

### ISSUE THREAD

**Issue by pseyfert** [andreasfertig/cppinsights#178]
I was wondering about [this example](https://cppinsights.io/lnk?code=c3RydWN0IFh7CiAgaW50IGYoKTsKICBpbnQgZihpbnQpOwogIGludCBmKGRvdWJsZSk7Cn07CgpzdHJ1Y3QgWTpYIHsKICBpbnQgZihmbG9hdCk7CiAgdXNpbmcgWDo6ZjsKfTsKCmludCBkb3RoaW5ncygpIHsKICBZIHk7CiAgaW50IG9uZSA9IHkuZigzLjEzKTsKICBpbnQgdHdvID0geS5mKDMuMTNmKTsKICByZXR1cm4gb25lK3R3bzsKfQ==&insightsOptions=cpp17&std=cpp17&rev=1.0) (source quoted below).

`Y` has an overload set for `f` that container `int f()`, `int f(int)`, `int
f(double)`, `int f(float)` but from the class declaration to the human reader
only `f(float` is visible and `using X::f` suggests there are more.

Does it make sense to spell out the using declared overload set in
cppinsights.io?

I think it would be nice to see what one imports with the using declaration.

I see in cppinsights one can somewhat infer what's going on on the call site

```cpp
int one = static_cast<X&>(y).f(...)
```
vs
```cpp
int two = y.f(...)
```

This reveals from which class `f` is used. But the full overload set for `f` is
not visible.

Opinions/comments?

## class sources

```cpp
struct X{
  int f();
  int f(int);
  int f(double);
};

struct Y:X {
  int f(float);
  using X::f;
};
```

**Comment by andreasfertig** [comment]
Hello @pseyfert,

great idea, I like it. I will look how and when I add it.

Andreas
