### ISSUE TITLE
support expand macro

### ISSUE THREAD

**Issue by meritozh** [andreasfertig/cppinsights#193]
Support expanding macro is very useful.

**Comment by andreasfertig** [comment]
Hello @meritozh,

can you be more specific? For example, the following code gets expanded:

```C++
#define MY_MACRO(x) (x*2)

int main()
{
  return MY_MACRO(4);
}
````

See [here](https://cppinsights.io/lnk?code=I2RlZmluZSBNWV9NQUNSTyh4KSAoeCoyKQoKaW50IG1haW4oKQp7CiAgcmV0dXJuIE1ZX01BQ1JPKDQpOwp9&insightsOptions=cpp17&std=cpp17&rev=1.0)

Andreas

**Comment by meritozh** [comment]
@andreasfertig demo [here](https://cppinsights.io/lnk?code=dGVtcGxhdGUgPHR5cGVuYW1lIFZhbCwgdHlwZW5hbWUgVGFnPgpjbGFzcyBydWxlX3Qge307CgojZGVmaW5lIGNwcGNtYl9wcmVsdWRlX2NhdCh4LCB5KSB4ICMjIHkKCiNkZWZpbmUgY3BwY21iX2NhdCh4LCB5KSBjcHBjbWJfcHJlbHVkZV9jYXQoeCwgeSkKCiNkZWZpbmUgY3BwY21iX3VuaXF1ZV9pZChwcmVmaXgpIGNwcGNtYl9jYXQocHJlZml4LCBfX0xJTkVfXykKCiNkZWZpbmUgY3BwY21iX2RlY2wobmFtZSwgLi4uKSBcCmF1dG8gY29uc3QgbmFtZSA9ICAgICAgICAgICAgICBcCnJ1bGVfdDxfX1ZBX0FSR1NfXywgc3RydWN0IGNwcGNtYl91bmlxdWVfaWQoY3BwY21iX3J1bGVfdGFnKT4oKQoKY3BwY21iX2RlY2woZXhwcl90b3AsIGludCk7&insightsOptions=cpp17&std=cpp17&rev=1.0). code copied from [CppCmb](https://github.com/LPeter1997/CppCmb).

macros only expanded under some conditions?

**Comment by andreasfertig** [comment]
Thank you. I will have a look at it.

**Comment by andreasfertig** [comment]
Hello @meritozh,

I have found the bug. A fix is on its way. Thank you for improving C++ Insights with your feedback. A few other cases in the tests are now also better.

Andreas
