### ISSUE TITLE
cppinsights loses `template<>` in explicit function template specializations

### ISSUE THREAD

**Issue by languagelawyer** [andreasfertig/cppinsights#200]
For the following code
```c++
template<typename U, typename ...T>
void f(U, T... rest)
{
  if constexpr (sizeof...(rest) != 0)
    f(rest...);
}

template<>
void f<int>(int) {}

int main()
{
    f(0, 1);
}
```
[cppinsights produces](https://cppinsights.io/lnk?code=dGVtcGxhdGU8dHlwZW5hbWUgVSwgdHlwZW5hbWUgLi4uVD4Kdm9pZCBmKFUsIFQuLi4gcmVzdCkKewogIGlmIGNvbnN0ZXhwciAoc2l6ZW9mLi4uKHJlc3QpICE9IDApCiAgICBmKHJlc3QuLi4pOwp9Cgp0ZW1wbGF0ZTw+CnZvaWQgZjxpbnQ+KGludCkge30KCmludCBtYWluKCkKewogICAgZigwLCAxKTsKfQ==&insightsOptions=cpp17&std=cpp17&rev=1.0)
```c++
template<typename U, typename ...T>
void f(U, T... rest)
{
  if constexpr (sizeof...(rest) != 0)
    f(rest...);
}

/* First instantiated from: insights.cpp:13 */
#ifdef INSIGHTS_USE_TEMPLATE
template<>
void f<int, int>(int, int __rest1)
{
  if constexpr(1 != 0) f(__rest1);
  
  
}
#endif


void f<int, >(int)
{
}


int main()
{
  f(0, 1);
}
```
Note that there is no `template<>` before the explicit specialization
```c++
void f<int, >(int)
{
}
```
Maybe because explicit specializations look similar to ordinary function declarations in the AST:
```
TranslationUnitDecl
|-FunctionTemplateDecl <line:1:1, line:6:1> line:2:6 f
...
| `-FunctionDecl <line:2:1, line:6:1> line:2:6 used f 'void (int, int)'
|   |-TemplateArgument type 'int'
|   |-TemplateArgument pack
|   | `-TemplateArgument type 'int'
...
|-FunctionDecl prev 0x5611456d1ff8 <line:8:1, line:9:19> col:6 used f 'void (int)'
| |-TemplateArgument type 'int'
| |-TemplateArgument pack
| |-ParmVarDecl <col:13> col:16 'int'
| `-CompoundStmt <col:18, col:19>
```
The `f<int, int>` instantiation is a child of the `FunctionTemplateDecl`, but the explicit specialization is not. It is a direct child of the `TranslationUnitDecl`.

However, an ordinary function declaration would not have the `prev 0xXXX...` part and `TemplateArgument`s. `void f(int) {}` is turned into
```
|-FunctionDecl <line:11:1, col:14> col:6 f 'void (int)'
| |-ParmVarDecl <col:8> col:11 'int'
| `-CompoundStmt <col:13, col:14>
```

**Comment by andreasfertig** [comment]
Hello @languagelawyer,

thank you for the detailed analysis! This gave me a good glue where to look.

Andreas
