### ISSUE TITLE
volatile qualifier is moved from member function to its return type

### ISSUE THREAD

**Issue by languagelawyer** [andreasfertig/cppinsights#201]
```c++
struct S
{
  void f() volatile;
};
```
is translated into
```c++
struct S
{
  volatile void f();
  
};
```

`const`, `&` and `&&` function qualifiers seem to be handled correctly.

**Comment by andreasfertig** [comment]
Hello @languagelawyer,

thank you for constantly improving C++ Insights! A fix is on its way.

Andreas
