### ISSUE TITLE
[HELP] problem about endianness

### ISSUE THREAD

**Issue by kakaducsy** [andreasfertig/cppinsights#207]
source: 
```cpp
#include <cstdio>
int main()
{
    char arr = 0x11;
    printf("c=%c\n", arr);
    return 0;
} 
```
Insight: 
```cpp
 #include <cstdio>
int main()
{
  char arr = 17;
  printf("c=%c\n", static_cast<int>(arr));
  return 0;
}
```
my understand that, the output of code above in Little endian machine and Big endian machine  not the same, Is it correct?

**Comment by andreasfertig** [comment]
Hello @kakaducsy,

if I'm not mistaken, then it depends in the implementation of `printf`.

Andreas
