### ISSUE TITLE
Add example for : destructors are implicitly noexcept

### ISSUE THREAD

**Issue by viboes** [andreasfertig/cppinsights#225]
The tool take cre already of implicit noexcept for destructors

https://cppinsights.io/s/f0e3aba8

Wondering if adding an it on the list of features and examples isn't a good idea.

**Comment by andreasfertig** [comment]
Hello @viboes,

I never thought about that. Feel free to submit a patch in the [cppinsights-web](https://github.com/andreasfertig/cppinsights-web/blob/master/app/static/examples.html) repo. There you can add an example you find most compelling.

Andreas

**Comment by viboes** [comment]
Unfortunately I'll not have access to my developement environment soon, as my PC is completly broken and I don't know yet what to replace it for. I will see if I can make some PR using the github interface at least for what concerns the documentation.

**Comment by andreasfertig** [comment]
Hello @viboes,

since nothing has happened here for a long time, I'm closing this issue.

Andreas
