### ISSUE TITLE
Replace the use of comments for special operation by =default, =delete declarations

### ISSUE THREAD

**Issue by viboes** [andreasfertig/cppinsights#232]
As for Display the special operations generated by the compiler #224 discussion, it is not clear the use of comments is better than using =default declarations.

Having a =default declaration is not considered as a user defined operation and shouldn't change the behavior.

I could be wrong, and an example would be more than welcome. We learn something new in C++ everyday and you tool will help a lot of people in this sense.

**Comment by viboes** [comment]
I don't know why this has changed since C++17 to C++20, but in C++17 an agrregate made the distiction between user declared and provided.

C++17
         no user-provided, inherited, or explicit constructors (explicitly defaulted or deleted constructors are allowed) 

C++20
         no user-declared or inherited constructors 

IMO, there is an CWG issue, as we moved since C++03 to C++17 to allow everytime more types that can be aggregates.


As for POD nothing has changed fortunately.

https://wandbox.org/permlink/dFMIQKVPxvIkmkwt

**Comment by viboes** [comment]
I've found the paper that did the change
http://open-std.org/JTC1/SC22/WG21/docs/papers/2018/p1008r0.pdf
But, i've not found why 

struct X {
  X() = default;
};

couldn't be an aggregate.

The wording is wrong IMNSHO.

All the reported cases had a condition by which aggregate initialization had no sense. Buth this basic case, is for me equivalent to don't addding it. The same for each one of the special operations.

**Comment by viboes** [comment]
I'm asking on cpplang slack and it seems I'm not the only one that finds that thi sis weird and a regression.

**Comment by ArtemSarmini** [comment]
@viboes it was a defect
> he author of class X could alternatively consider making the default constructorprivate. But ifthis constructor is given a defaulted definition, this again does not prevent aggregate initialization(and thus, instantiation) of the class:
````
struct X {
private:
    X() = default;
};
int main() {
    X x1;// ill-formed - default c’tor is private
    X x2{};// compiles!
````



> Because of the current rules, aggregate initialization allows us to “default-construct” a class even ifit is not, in fact, default-constructible

**Comment by andreasfertig** [comment]
Hello @viboes,

as using `=default` makes a difference here, I will keep the statements as comments. Treading this issue as NAD.

Andreas
