### ISSUE TITLE
Add a limitation respect to the enerated  =deleted special operations

### ISSUE THREAD

**Issue by viboes** [andreasfertig/cppinsights#233]
As for Display the special operations generated by the compiler #224 discussion, we have identified the tool do not transforms the special operations functions that are deleted by the compiler. This is surely due to the fact that the tool is based on the AST and this information is not still there.

When the user request the default and the compiler deletes the function as he default generated will be ill formed, the tool could replace =default by =delete.

Before

struct C
{
  int & i;
  C() = default;
  C(const C &) = default;
};

https://cppinsights.io/s/cd13011a

After

struct C
{
  int & i;
  inline C() = delete;
  inline C(const C &) = delete;
};

I believe that the documentation could report this limitation on a specific section

**Comment by andreasfertig** [comment]
Hello @viboes,

that is a nice finding, thank you. I will push a fix for it.

Andreas

**Comment by viboes** [comment]
Thanks a lot. This is super useful for people that are learning.

BTW, there was an error on my description.
The copy constructor is ok, but the copy assignment ends by being deleted.

**Comment by andreasfertig** [comment]
You're welcome!
