### ISSUE TITLE
ranged for-loop inside lambda crashes

### ISSUE THREAD

**Issue by hessbe** [andreasfertig/cppinsights#238]
this example crashes the conversion:
`void f() {
    auto lambda = [](auto container) {
      for(auto test : container) { }
    };
}`

also with a template instantiation:
`#include <vector>
void f() {
    auto lambda = [](auto container) {
      for(auto test : container) { }
    };
  
  std::vector<int> vec{1,2,3,4};
  lambda(vec);
}`

`[0x13449ff]
...
[0x4055aa]
Segmentation fault (core dumped)
`

**Comment by andreasfertig** [comment]
Hello @hessbe,

thank you! Nice finding. Here we have a range-based for-loop in an unevaluated context. Hence, not all the necessary information is present. My fix would be to show the range-based for-loop as it is in this cases. What do you think?

Andreas

**Comment by andreasfertig** [comment]
On a second thought, it is easier to transform it. This is more consistent and requires less special cases. Your initial example would then look like this:

```.cpp
void f()
{

  class __lambda_1_26
  {
    public:
    template<class type_parameter_0_0>
    inline /*constexpr */ auto operator()(type_parameter_0_0 container) const
    {
      {
        auto && __range1 = container;
        for(; ; )
        {
          auto test;
        }

      }
    }
    private:
    template<class type_parameter_0_0>
    static inline auto __invoke(type_parameter_0_0 container)
    {
      {
        auto && __range1 = container;
        for(; ; )
        {
          auto test;
        }

      }
    }

  };

  __lambda_1_26 lambda = __lambda_1_26{};
}
```

Andreas

**Comment by hessbe** [comment]
In my opinion that's good enough as long as the instantiation is correct. 

Or how difficult is it to show everything with auto? Like this:
`{
	auto& __range1 = container;
	auto __begin1 = __range1.begin();
	auto __end1 = __range1.end();
	for(; __gnu_cxx::operator!=(__begin1, __end1); __begin1.operator++()) 
	{
	  auto test = __begin1.operator*();
	  // content of loop
	}
}`

**Comment by andreasfertig** [comment]
Hello @hessbe,

difficult as at this point it is unknown. It can also be that `std::begin` or `std::end` is called. Same goes for the operators. Plus it requires special treatment. 
I prefer to transform what is there.

Andreas

**Comment by hessbe** [comment]
Hi Andrea,

I'm fully content with your proposed solution. I was preparing some examples for internal training and this crash popped up so I wanted to make sure you know about it. There was also a template instantiation In the example so the full solution would be shown there and that's all I wanted to show the team.

Ben

**Comment by andreasfertig** [comment]
Hello @hessbe,

excellent, and sorry for the trouble before your training. A fix is on its way.

Andreas
