### ISSUE TITLE
Casting in class error

### ISSUE THREAD

**Issue by jonathanberthias** [andreasfertig/cppinsights#24]
There is a small bug when casting is done with a class member. As an example:

```
class Simple 
{
    int p;
  public:
    double get() {return p;}
};
```

yields

```
class Simple 
{
    int p;
  public:
    double get() {return static_cast<double>(this->p)p;}
};
```

An additionnal `p` is added after the cast, making the resulting code uncompilable. 

Other than that, it is a great project !

**Comment by andreasfertig** [comment]
Hello Jonathan,

thank you! Fix is on its way.
