### ISSUE TITLE
template arguments for templated methods don't appear in cppinsights

### ISSUE THREAD

**Issue by pseyfert** [andreasfertig/cppinsights#254]
[demonstrator](https://cppinsights.io/lnk?code=c3RydWN0IGRlbW9uc3RyYXRvcnsKICB0ZW1wbGF0ZSA8dHlwZW5hbWUgcmV0dXJuX3R5cGUgPSBkb3VibGU+CiAgcmV0dXJuX3R5cGUgdGVtcGxhdGVkX2Z1bmN0aW9uKCkgewogICAgcmV0dXJuIHJldHVybl90eXBle307CiAgfQp9OwoKaW50IGRlbW9uc3RyYXRlKCkgewogIGRlbW9uc3RyYXRvciBEOwogIEQudGVtcGxhdGUgdGVtcGxhdGVkX2Z1bmN0aW9uPGJvb2w+KCk7CiAgRC50ZW1wbGF0ZSB0ZW1wbGF0ZWRfZnVuY3Rpb248ZmxvYXQ+KCk7CiAgRC50ZW1wbGF0ZSB0ZW1wbGF0ZWRfZnVuY3Rpb24oKTsKICByZXR1cm4gNDI7Cn0KICA=&insightsOptions=cpp17&std=cpp17&rev=1.0)

When dealing with a templated method of a struct, it appears that the template arguments of templated methods do not appear in the output of cppinsights:

```cpp
struct demonstrator{
  template <typename return_type = double>
  return_type templated_function() {
    return return_type{};
  }
};

int demonstrate() {
  demonstrator D;
  D.template templated_function<bool>();
  D.template templated_function<float>();
  D.template templated_function();
  return 42;
}
```

here all three `templated_function` calls appear just as `templated_function()` in the output.
Prefered would be printing the template parameters, including the default parameters

```cpp
  D.template templated_function<bool>();
  D.template templated_function<float>();
  D.template templated_function<double>();
```

(background, I was dealing with a range based for loop where `begin` and `end`
of the looped struct have template parameters. So while this looks unimportant
in the MWE it can be that the template parameters appear neither directly in
the user's source, nor the cppinsights output)

**Comment by andreasfertig** [comment]
Hello @pseyfert,

thanks for bringing that up. That indeed is an interesting case. I'll have a look into it and come back to you.

Andreas
