### ISSUE TITLE
resolved type names for types defined in class bodies lack their "namespace"

### ISSUE THREAD

**Issue by pseyfert** [andreasfertig/cppinsights#255]
comparing [this](https://cppinsights.io/lnk?code=I2luY2x1ZGUgPGNzdGRkZWY+CiNpbmNsdWRlIDx0dXBsZT4KI2luY2x1ZGUgPHZlY3Rvcj4KCnN0cnVjdCBJdGVyYWJsZSB7CiAgdXNpbmcgV2lkZ2V0ID0gc3RkOjp0dXBsZTxpbnQsIGZsb2F0PjsKICB0ZW1wbGF0ZSA8dHlwZW5hbWUgYWNjZXNzX3R5cGU+CiAgc3RydWN0IEl0ZXJhdG9yIHsKICAgIEl0ZXJhYmxlKiAgIG1faXRlcmFibGU7CiAgICBzdGQ6OnNpemVfdCBtX3BvczsKICAgIGJvb2wgICAgICAgIG9wZXJhdG9yPT0oIGNvbnN0IEl0ZXJhdG9yJiBvdGhlciApIHsgcmV0dXJuIG1faXRlcmFibGUgPT0gb3RoZXIubV9pdGVyYWJsZSAmJiBtX3BvcyA9PSBvdGhlci5tX3BvczsgfQogICAgYm9vbCAgICAgICAgb3BlcmF0b3IhPSggY29uc3QgSXRlcmF0b3ImIG90aGVyICkgeyByZXR1cm4gISggdGhpcy0+b3BlcmF0b3I9PSggb3RoZXIgKSApOyB9CiAgICBhY2Nlc3NfdHlwZSBvcGVyYXRvciooKSB7CiAgICAgIFdpZGdldCB0bXAgPSBtX2l0ZXJhYmxlLT5tX3N0b3JhZ2VbbV9wb3NdOwogICAgICByZXR1cm4gc3RkOjpnZXQ8YWNjZXNzX3R5cGU+KCB0bXAgKTsKICAgIH0KICAgIEl0ZXJhdG9yIG9wZXJhdG9yKysoKSB7CiAgICAgIG1fcG9zKys7CiAgICAgIHJldHVybiAqdGhpczsKICAgIH0KICB9OwogIHRlbXBsYXRlIDx0eXBlbmFtZSBhY2Nlc3NfdHlwZSA9IGludD4KICBJdGVyYXRvcjxhY2Nlc3NfdHlwZT4gYmVnaW4oKSB7CiAgICByZXR1cm4ge3RoaXMsIDB9OwogIH0KICB0ZW1wbGF0ZSA8dHlwZW5hbWUgYWNjZXNzX3R5cGUgPSBpbnQ+CiAgSXRlcmF0b3I8YWNjZXNzX3R5cGU+IGVuZCgpIHsKICAgIHJldHVybiB7dGhpcywgbV9zdG9yYWdlLnNpemUoKX07CiAgfQogIHN0ZDo6dmVjdG9yPFdpZGdldD4gbV9zdG9yYWdlOwp9OwoKdm9pZCB0ZXN0KCkgewogIEl0ZXJhYmxlIGNvbnRhaW5lcjsKICBmb3IgKCBhdXRvIGVsZW1lbnQgOiBjb250YWluZXIgKSB7IHN0YXRpY19hc3NlcnQoIHN0ZDo6aXNfc2FtZV92PGRlY2x0eXBlKCBlbGVtZW50ICksIGludD4gKTsgfQogIGZvciAoIGF1dG8gaXRlciA9IGNvbnRhaW5lci5iZWdpbjxmbG9hdD4oKTsgaXRlciAhPSBjb250YWluZXIuZW5kPGZsb2F0PigpOyArK2l0ZXIgKSB7CiAgICBzdGF0aWNfYXNzZXJ0KCBzdGQ6OmlzX3NhbWVfdjxkZWNsdHlwZSggKml0ZXIgKSwgZmxvYXQ+ICk7CiAgfQp9&insightsOptions=cpp2a&std=cpp2a&rev=1.0) and [this](https://cppinsights.io/lnk?code=I2luY2x1ZGUgPGNzdGRkZWY+CiNpbmNsdWRlIDx0dXBsZT4KI2luY2x1ZGUgPHZlY3Rvcj4KCm5hbWVzcGFjZSBURVNUUkVTT0xVVElPTiB7CnRlbXBsYXRlIDx0eXBlbmFtZSBhY2Nlc3NfdHlwZT4Kc3RydWN0IEl0ZXJhdG9yOwp9CnVzaW5nIFdpZGdldCA9IHN0ZDo6dHVwbGU8aW50LCBmbG9hdD47CgpzdHJ1Y3QgSXRlcmFibGUgewogIHRlbXBsYXRlIDx0eXBlbmFtZSBhY2Nlc3NfdHlwZSA9IGludD4KICBURVNUUkVTT0xVVElPTjo6SXRlcmF0b3I8YWNjZXNzX3R5cGU+IGJlZ2luKCkgewogICAgcmV0dXJuIHt0aGlzLCAwfTsKICB9CiAgdGVtcGxhdGUgPHR5cGVuYW1lIGFjY2Vzc190eXBlID0gaW50PgogIFRFU1RSRVNPTFVUSU9OOjpJdGVyYXRvcjxhY2Nlc3NfdHlwZT4gZW5kKCkgewogICAgcmV0dXJuIHt0aGlzLCBtX3N0b3JhZ2Uuc2l6ZSgpfTsKICB9CiAgc3RkOjp2ZWN0b3I8V2lkZ2V0PiBtX3N0b3JhZ2U7Cn07CgpuYW1lc3BhY2UgVEVTVFJFU09MVVRJT04gewoKdGVtcGxhdGUgPHR5cGVuYW1lIGFjY2Vzc190eXBlPgpzdHJ1Y3QgSXRlcmF0b3IgewogIEl0ZXJhYmxlKiBtX2l0ZXJhYmxlOwogIHN0ZDo6c2l6ZV90IG1fcG9zOwogIGJvb2wgb3BlcmF0b3I9PShjb25zdCBJdGVyYXRvciYgb3RoZXIpIHsKICAgIHJldHVybiBtX2l0ZXJhYmxlID09IG90aGVyLm1faXRlcmFibGUgJiYgbV9wb3MgPT0gb3RoZXIubV9wb3M7CiAgfQogIGJvb2wgb3BlcmF0b3IhPShjb25zdCBJdGVyYXRvciYgb3RoZXIpIHsgcmV0dXJuICEodGhpcy0+b3BlcmF0b3I9PShvdGhlcikpOyB9CiAgYWNjZXNzX3R5cGUgb3BlcmF0b3IqKCkgewogICAgV2lkZ2V0IHRtcCA9IG1faXRlcmFibGUtPm1fc3RvcmFnZVttX3Bvc107CiAgICByZXR1cm4gc3RkOjpnZXQ8YWNjZXNzX3R5cGU+KHRtcCk7CiAgfQogIEl0ZXJhdG9yIG9wZXJhdG9yKysoKSB7CiAgICBtX3BvcysrOwogICAgcmV0dXJuICp0aGlzOwogIH0KfTsKfSAgLy8gbmFtZXNwYWNlIFRFU1RSRVNPTFVUSU9OCgp2b2lkIHRlc3QoKSB7CiAgSXRlcmFibGUgY29udGFpbmVyOwogIGF1dG8gdGVzdCA9IGNvbnRhaW5lci5iZWdpbigpOwogIGZvciAoYXV0byBlbGVtZW50IDogY29udGFpbmVyKSB7CiAgICBzdGF0aWNfYXNzZXJ0KHN0ZDo6aXNfc2FtZV92PGRlY2x0eXBlKGVsZW1lbnQpLCBpbnQ+KTsKICB9CiAgZm9yIChhdXRvIGl0ZXIgPSBjb250YWluZXIuYmVnaW48ZmxvYXQ+KCk7IGl0ZXIgIT0gY29udGFpbmVyLmVuZDxmbG9hdD4oKTsKICAgICAgICsraXRlcikgewogICAgc3RhdGljX2Fzc2VydChzdGQ6OmlzX3NhbWVfdjxkZWNsdHlwZSgqaXRlciksIGZsb2F0Pik7CiAgfQp9&insightsOptions=cpp2a&std=cpp2a&rev=1.0) example, there is a custom iterator class in both cases.

Abbreviated, in the former, the iterator definition is in another class
```cpp
struct Iterable {
  struct Iterator {
  };
};
```

In the latter, the iterator is defined in some namespace
```cpp
namespace MYNAMESPACE {
  struct Iterator {
  };
}
struct Iterable {
};
```

In both cases `Iterable::begin()` returns an `Iterator`.
Yet, in the cppinsights output, the former iterator appears as `Iterator` instead of `Iterable::Iterator`. In the latter case, the leading `MYNAMESPACE::` is printed correctly.

I think it would be nice if the leading `Iterable::` would also be printed in the former case (for disambiguation, should someone run into a case where that's necessary), and such that the printout of cppinsights is valid code.

**Comment by andreasfertig** [comment]
Hello @pseyfert,

thank you for reporting this. I'll look into it.

Andreas
