### ISSUE TITLE
Support Boost headers

### ISSUE THREAD

**Issue by pgroke-dt** [andreasfertig/cppinsights#263]
Hi,

having Boost headers available would be good. Boost contains many libraries that feature entirely non-trivial code. Having a tool like cppinsights available that can help answer questions like which conversions are invoked, which overloads are being selected etc. would be nice.

Of course the ideal solution would be something like Matt Godbolt's awsome Compiler Explorer has where you can select which version of which library you need. But a recent-ish Boost version would already be an improvement :)

**Comment by andreasfertig** [comment]
Hello @pgroke-dt,

that is an interesting enhancement. I totally see the benefit. However, I also see the increased maintenance that comes with it. I have to think about the long-time implications a bit more. 

Andreas

**Comment by pgroke-dt** [comment]
I think it would be nice to have it. But I completely understand if you decide it's too much work :)
BTW: Maybe you could team up with Matt Godbolt to merge this functionality into Compiler Explorer? Because this would be really awesome!

**Comment by andreasfertig** [comment]
Great, thank you!

I understand that for some reasons it would be great in Compiler Explorer. For the moment I like it as it is. I think with the current way users can get more context about what C++ Insights is and does. Plus issues reports get straight to me.

Andreas

**Comment by pgroke-dt** [comment]
It would not necessarily have to be a feature hosted on godbolt.org. I was just thinking since Compiler Explorer is open source it could be possible to maybe use its container deployment scripts or something. IDK how reusable that stuff it, but if it is it would be great because there's a ton of libraries available on Compiler Explorer.

Anyway, it was just an idea. I of course respect if you don't like it for whatever reasons :)

**Comment by jfeep** [comment]
I bumped into this issue recently.  Any update on plans for availability of Boost libraries within cppinsights?

**Comment by andreasfertig** [comment]
Hello @pgroke-dt,

after a very long time, sorry about that, I finally decided to add support for boost (https://github.com/andreasfertig/cppinsights-container/commit/013e48460ba5f0fb695224a5ebc9db1ca833c773).

The current version information can be found here: [https://cppinsights.io/version](https://cppinsights.io/version). Right now boost 1_83_0 is used.

Andreas

**Comment by pgroke-dt** [comment]
Hi @andreasfertig ,

thanks so much for implementing this! :) I'm sure it will come in handy.

Paul
