### ISSUE TITLE
The name of a variable of type "pointer to member" is misplaced

### ISSUE THREAD

**Issue by languagelawyer** [andreasfertig/cppinsights#279]
For the code
```c++
struct S { void f(); };

int main()
{
    auto p = &S::f;
}
```
[cppinsights produces](https://cppinsights.io/lnk?code=c3RydWN0IFMgeyB2b2lkIGYoKTsgfTsKCmludCBtYWluKCkKewogICAgYXV0byBwID0gJlM6OmY7Cn0=&insightsOptions=cpp17&std=cpp17&rev=1.0)
```c++
struct S
{
  void f();
  
};



int main()
{
  void (S::*)() p = &S::f;
}

```
while it should have produced
```c++
struct S
{
  void f();
  
};



int main()
{
  void (S::*p)() = &S::f;
}
```

**Comment by andreasfertig** [comment]
Hello @languagelawyer,

thank you for your continous support and bug reports! A fix is on its way.

Andreas
