### ISSUE TITLE
ConstexprVariableCase duplicated in clang-tidy options file

### ISSUE THREAD

**Issue by zorg93** [andreasfertig/cppinsights#280]
https://github.com/andreasfertig/cppinsights/blob/128d05d4c706ed8a4cbe49b605836a356fbc0137/.clang-tidy#L12
https://github.com/andreasfertig/cppinsights/blob/128d05d4c706ed8a4cbe49b605836a356fbc0137/.clang-tidy#L20

**Comment by andreasfertig** [comment]
Hello @zorg93,

thank you for spotting this!

Andreas
