### ISSUE TITLE
`decltype` isn't resolved when followed by `&`

### ISSUE THREAD

**Issue by niklasnolte** [andreasfertig/cppinsights#286]
https://cppinsights.io/s/6f62be64 vs https://cppinsights.io/s/8b0c93a7

In the case where the decltype(v) is followed by &, the type does not get resolved.
Is this wanted behaviour?

**Comment by andreasfertig** [comment]
Hello @niklasnolte,

thank you for spotting & reporting this. I consider it a bug and not the wanted behaviour. A fix is on its way.

Andreas

**Comment by niklasnolte** [comment]
thanks for the quick fix @andreasfertig !
