### ISSUE TITLE
Compilation fails for code using __float128 (libquadmath)

### ISSUE THREAD

**Issue by TiborGY** [andreasfertig/cppinsights#295]
Demonstration : [https://cppinsights.io/s/ebf124a0](url)

**Comment by andreasfertig** [comment]
Hello @TiborGY,

the relevant header or better library is not installed for the web-version of C++ Insights. Currently, there are no additional libraries, as for example Compiler Explorer provides them. As it increases maintainability effort I tend to keep this kind of dependencies minimal. May I ask what you like to see here and why `libquadmath0` should be part of C++ Insights?

Andreas
