### ISSUE TITLE
Call of `template <typename T> void fun (T&& t) { };` leads to segfault

### ISSUE THREAD

**Issue by rrika** [andreasfertig/cppinsights#298]
```c++
template <typename T> void fun (T&& t) { };
void test() { fun(1); }
```
https://cppinsights.io/s/4939edc0

**Comment by andreasfertig** [comment]
Hello @rrika,

thank you for reporting this issue. I haven't figured out how to fix it yet. However, as a quick fix, in case you like to see the result, remove the semi-colon at the end of line 1.

Andreas
