### ISSUE TITLE
Cppinsights loses alignas specifications

### ISSUE THREAD

**Issue by ilyapopov** [andreasfertig/cppinsights#311]
See https://cppinsights.io/lnk?code=c3RydWN0IGFsaWduYXMoZG91YmxlKSBmb28gewogICAgaW50IGk7Cn07CgpzdGF0aWNfYXNzZXJ0KHNpemVvZihmb28pID09IDgpOwo=&insightsOptions=cpp2a&std=cpp2a&rev=1.0

**Comment by andreasfertig** [comment]
Hello @ilyapopov,

thank for reporting this. `alignas` is modeled as an attribute in Clang. Currently, there is no implementation to support attributes in C++ Insights. They are missing in other places like `[[no_return]]` and more. However, I'm working on it, as `consteval`/`consteval` are modeled as an attribute as well.

Andreas
