### ISSUE TITLE
How to get the expected generated c++ code with cppinsights ?

### ISSUE THREAD

**Issue by preejackie** [andreasfertig/cppinsights#34]
How to get the generated c++ source code (with compiler generated code)? Are there any special commands I have to pass along with "clang++ -std=cxx source_code.cpp " while compiling the source code? 
Thanks

**Comment by andreasfertig** [comment]
Hello preejackie,

I'm not sure I understand the question. Do you aim to achieve the transformation as the web client shows it? Then it would be roughly: ./insights source_code.cpp -- -std=c++1z and probably the include path(s).
