### ISSUE TITLE
Reference to type alias denoting an array type is mishandled in function return type

### ISSUE THREAD

**Issue by languagelawyer** [andreasfertig/cppinsights#341]
```c++
using arr_t = int[10];

arr_t* f();
arr_t& g();
arr_t&& h();
```
turns into
```c++
using arr_t = int[10];

arr_t (*f());

arr_t &;

arr_t &&;

```
There is no `g` and `h` in the cppinsights output.

**Comment by andreasfertig** [comment]
Hello @languagelawyer,

I haven't received an issue report from you for a while. Glad you are still using and reporting issues for C++ Insights! Thank you for catching and reporting this one. A fix is on its way.

Andreas
