### ISSUE TITLE
vscode extension

### ISSUE THREAD

**Issue by lingjf** [andreasfertig/cppinsights#342]
i want to use it in vscode as extension conveniently.

**Comment by andreasfertig** [comment]
Hello @lingjf,

thank you for raising that request. Unfortunately, I'm not a vscode user. I have no idea how an extension has to look like. From your short request, it is unclear to me what exactly that extension should do. Transform an entire project, only a selected part of the code... Maybe you could elaborate a bit more on that. Feel free to send a PR. I'm happy to leave this request, with more details, open for a while tagged as "help wanted" to see if anyone likes to jump in.

Andreas

**Comment by lingjf** [comment]
i also have no idea how it works in vscode now, but i try to write one.

**Comment by TerensTare** [comment]
We can try to propose this to the vscode C/C++ extension team if this is still of interest. I use vscode and I'm pretty sure there are other people who are interested in this. As for what it should look like, vscode has a "Markdown Preview" feature which has the same layout as the CppInsights one, so the layout should be relatively trivial to implement.

Terens

**Comment by andreasfertig** [comment]
Hello @TerensTare,

I'm open to that idea to approach the vscode team. Just, I'm not a vscode user, so I cannot say exactly what is wanted and how it should look. If you like to propose this extension to the vscode team that would be great.

Andreas

**Comment by i-ky** [comment]
I'm interested in VS Code support too, but I don't like the idea of baking this functionality into C/C++ extension. The best thing about VS Code is modularity. However, C/C++ extension already violates this principle by providing both highlighting/autocompletion and debugging capabilities. Their debugging has no alternatives, but there are other extensions (clangd and ccls) providing highlighting/autocompletion. It is a bit of a pain to combine debugging by C/C++ extension with highlighting/autocomplete by clangd or ccls. Please keep cppinsights as a standalone extensions.

I would be very glad to help, but being a C/C++ developer I not very good at Javascript, Typescript and other web technologies VS Code is based on.

**Comment by devtbi** [comment]
I've created https://github.com/devtbi/vscode-cppinsights. Still in it's very early stages, but it publishes two commands to translate a file with insights and diff it with the original.

Don't think any dependency to the C/C++ extension is necessary, since clang tools support a compilation database - no additional info should be required.

**Comment by andreasfertig** [comment]
Hello @devtbi,

thank you! That's a great addition for vscode. As I have no vscode would you mind adding some screenshots? You can add it to the C++ Insights Readme.md to make people aware of it. I will tweet about it. If you send me your Twitter handle (via PM if you want) I can credit you directly in the tweet.

Andreas

**Comment by devtbi** [comment]
hi @andreasfertig,

yes I'll add a screenshot. It's very simplistic, just opens another editor aside of the original with the equally formatted output/ or a diff view (unfortunately haven't yet figured out how to get the same formatting there).

Anyhow, i'll try to spend some more time this week to get it to a state where I can upload a first version to the vscode extension "marketplace". Probably makes sense to tweet/add it to the cppinsights readme at that point?

twitter handle is @meet__tobi (double underscore)

**Comment by devtbi** [comment]
hi there, @andreasfertig @i-ky @TerensTare @lingjf,
i've published the extension as a preview to the marketplace. Let me know if you have any feedback.

**Comment by devtbi** [comment]
@andreasfertig can I use the logo for the vscode extension?

**Comment by andreasfertig** [comment]
Hello @devtbi,

the extension looks great! Thank you!

Yes, you can use the C++ Insights logo for the vscode extension.

May I ask, how do you pass snippets to C++ Insights? I wonder if we need additional tests in C++ Insights to ensure that this API remains stable.

Andreas

**Comment by devtbi** [comment]
hi @andreasfertig,

thanks :)

Not sure what you mean. As of now, the extension only works on file basis. Either the file is saved, then I use the the original file path an pass it to insights, or it's an unsaved file. In that case, I write the editor contents to a temp file and pass that to insights.

Always calling insights like this: `<path> <file> [-p <buildDirectory>] [--extra-arg <arg1> --extra-arg <arg2> ...]`
