### ISSUE TITLE
Auto param in lada expression result doesn't compile

### ISSUE THREAD

**Issue by korelkashri** [andreasfertig/cppinsights#346]
Consider the following input:

```cpp
#include <iostream>

int main() {
	auto lambda = [](auto a, auto b) {
    	return a + b;
	};
	return EXIT_SUCCESS;
}
```

The result will be:

```cpp
#include <iostream>

int main()
{
    
  class __lambda_4_16
  {
    public: 
    template<class type_parameter_0_0, class type_parameter_0_1>
    inline /*constexpr */ auto operator()(type_parameter_0_0 a, type_parameter_0_1 b) const
    {
      return a + b;
    }
    
    #ifdef INSIGHTS_USE_TEMPLATE
    template<>
    inline /*constexpr */ double operator()(int a, double b) const
    {
      return static_cast<double>(a) + b;
    }
    #endif
    
    
    #ifdef INSIGHTS_USE_TEMPLATE
    template<>
    inline /*constexpr */ float operator()(float a, int b) const
    {
      return a + static_cast<float>(b);
    }
    #endif
    
    private: 
    template<class type_parameter_0_0, class type_parameter_0_1>
    static inline auto __invoke(type_parameter_0_0 a, type_parameter_0_1 b)
    {
      return a + b;
    }
    
    public:
    // /*constexpr */ __lambda_4_16() = default;
    
  };
  
  __lambda_4_16 lambda = __lambda_4_16{};
  lambda.operator()(1, 2.3999999999999999);
  lambda.operator()(5.0F, 3);
  return 0;
}
```
If you'll take this result and compile it, it won't compile with a compilation error:

```cpp
/home/insights/insights.cpp:9:5: error: templates cannot be declared inside of a local class
    template<class type_parameter_0_0, class type_parameter_0_1>
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

To make it compile, you have to declare the class outside the `main` scope:

```cpp
#include <iostream>

class __lambda_4_16
{
  public: 
  template<class type_parameter_0_0, class type_parameter_0_1>
    inline /*constexpr */ auto operator()(type_parameter_0_0 a, type_parameter_0_1 b) const
  {
    return a + b;
  }

  #ifdef INSIGHTS_USE_TEMPLATE
  template<>
  inline /*constexpr */ double operator()(int a, double b) const
  {
    return static_cast<double>(a) + b;
  }
  #endif


  #ifdef INSIGHTS_USE_TEMPLATE
  template<>
  inline /*constexpr */ float operator()(float a, int b) const
  {
    return a + static_cast<float>(b);
  }
  #endif

  private: 
  template<class type_parameter_0_0, class type_parameter_0_1>
    static inline auto __invoke(type_parameter_0_0 a, type_parameter_0_1 b)
  {
    return a + b;
  }

  public:
  // /*constexpr */ __lambda_4_16() = default;

};

int main() {
  __lambda_4_16 lambda = __lambda_4_16{};
  lambda.operator()(1, 2.3999999999999999);
  lambda.operator()(5.0F, 3);
  return 0;
}
```

Now about the function explicit specialization. It's not allowed inside a non-namespace scope. To solve this issue (you'll get an error without the `ifndef` guard) remove the `template<>` before the function ([as suggested by @bop on StackOverflow](https://stackoverflow.com/a/13018943/8038186)):

```cpp
class __lambda_4_16
{
  public: 
  template<class type_parameter_0_0, class type_parameter_0_1>
    inline /*constexpr */ auto operator()(type_parameter_0_0 a, type_parameter_0_1 b) const
  {
    return a + b;
  }

  inline /*constexpr */ double operator()(int a, double b) const
  {
    return static_cast<double>(a) + b;
  }

  inline /*constexpr */ float operator()(float a, int b) const
  {
    return a + static_cast<float>(b);
  }
  
  private: 
  template<class type_parameter_0_0, class type_parameter_0_1>
    static inline auto __invoke(type_parameter_0_0 a, type_parameter_0_1 b)
  {
    return a + b;
  }

  public:
  // /*constexpr */ __lambda_4_16() = default;

};
```

**Comment by andreasfertig** [comment]
Hello @korelkashri,

thanks for bringing this up. You are right. As users, we are not allowed to define a class template inside a function. We are also not allowed to provide a specialization inside a class.

However, there are two things. First, it is more complex than moving the closure type before `main`. Consider this example:

```C++
template<typename T>
void Fun(T&&)  {}

void AnotherFun() {}

int main()
{
  Fun([]{});
}
```

To make it compile, the closure type must not just go before `main`. It needs to be before its first usage. Doable but more complex, especially if it comes to method templates.

The second thing is the way C++ Insights shows it currently, is the way the compiler does it. See [eel.is/c++draft/expr.prim.lambda](http://eel.is/c++draft/expr.prim.lambda#closure-2):
>The closure type is declared in the smallest block scope, class scope, or namespace scope that contains the corresponding lambda-expression. ...

This is a no-win situation where either the code compiles or is more what the Standard mandates. In this case, I chose to be close to the Standard.

Andreas

**Comment by korelkashri** [comment]
I can't disagree with you :)
Although I think that the win situation is to be closer to the standard with a note the this code might not compile (in cases it won't) and that it's this way to avoid unnecessary complexity when understanding is in need.

**Comment by andreasfertig** [comment]
Hello @korelkashri,

true. My fear is that comments like these plus some other annotations you suggested are then all over the code and generate to much noise. In another issue it was suggested to put information like this in the docs ([docs.cppinsights.io/](https://docs.cppinsights.io/)) which is think is the better option. They are generated from here [github.com/andreasfertig/cppinsights/tree/master/docs](https://github.com/andreasfertig/cppinsights/tree/master/docs), feel free to contribute.

   Andreas
