### ISSUE TITLE
Incorrect alias type naming of aliases for pointer to member types

### ISSUE THREAD

**Issue by mfurkanuslu** [andreasfertig/cppinsights#349]
For example for this input;
```auto m = &S::mem;```

The output is:
```
using FuncPtr_7 = int S::*;
FuncPtr_7 m = &S::mem;
```
But m is actually a pointer to member variable.

**Comment by andreasfertig** [comment]
Hello @mfurkanuslu,

thanks for bringing this up. Can you please provide a full example? That helps for tests later and me to understand what you see that is wrong here. I'm not clear on that. Do you say something is invalid C++ in the transformation of your example, or do you say `FuncPtr_7` should be named something like `MemVarPtr`?

Andreas

**Comment by mfurkanuslu** [comment]
> or do you say FuncPtr_7 should be named something like MemVarPtr?
Yes.

**Comment by andreasfertig** [comment]
Hello @mfurkanuslu,

thanks for the clarification. A fix is on its way.

Andreas
