### ISSUE TITLE
Incorrect constructor in return statement

### ISSUE THREAD

**Issue by adromanov** [andreasfertig/cppinsights#351]
Consider the following code:
```#include <optional>

struct A {};

struct Test
{
    Test(const A &);
    Test(A &&);
};

std::optional<Test> foo()
{
    A a;
    return a;
}
```
in `return` statement constructor from rvalue reference is called [(https://gcc.godbolt.org/z/KeWb4e)](https://gcc.godbolt.org/z/KeWb4e). This is due to [https://en.cppreference.com/w/cpp/language/return](https://en.cppreference.com/w/cpp/language/return) "Automatic move from local variables and parameters" part. This also could be seen in AST.
However, the output is (for the `foo()`):
```
std::optional<Test> foo()
{
  A a = A();
  return std::optional<Test>(a);
}
```
Here lvalue refeference constructor is called.

**Comment by andreasfertig** [comment]
Hello @adromanov,

thanks for reporting this interesting issue. I think you uncovered a bigger issue with `ImplicitCastExpr`s in general. With your example, I think an `ImplicitCastExpr` with `NoOp` and an `xvalue` needs to be shown. I'm running some tests and try to figure out how to handle it correctly. 

Andreas
