### ISSUE TITLE
Duplication of attribute specifier

### ISSUE THREAD

**Issue by Rb37** [andreasfertig/cppinsights#354]
This example:
```cpp
unsigned __attribute__((const))
ctz(unsigned x)
{
	return 0;
}
```
expands as:
```cpp
unsigned __attribute___attribute__((const)) unsigned int ctz(unsigned int x)
{
  return 0;
}
```
This leads to duplication of `unsigned` and `__attribute__`

**Comment by andreasfertig** [comment]
Hello @Rb37,

my apologies but I totally overlooked this issue. Thanks for reporting it. A fix is on its way.

Andreas
