### ISSUE TITLE
initializing static variables

### ISSUE THREAD

**Issue by fekir** [andreasfertig/cppinsights#369]
Since c++11, static variables are initialized thread-safely once in case of success.

cppinsights shows this correctly for 

```
struct foo{foo();};

const foo& create(){
	static foo value = foo(); // exception handling is there
  	return value;
}
```

(ie and `catch(...)` with `__cxa_guard_abort` is present)

but does not for those variants (adding const or an indirection through a lambda or function)

```
struct foo{foo();};

const foo& create(){
  	static const foo value = foo(); // exception handling missing
  	return value;
}
```

```
struct foo{foo();};

const foo& create(){
  	static foo value = [](){return foo();}(); // exception handling missing
  	return value;
}
```

```
struct foo{foo();};

foo make_foo(){
	return foo();
}

const foo& create(){
	static foo value = make_foo(); // exception handling missing
  	return value;
}
```

**Comment by andreasfertig** [comment]
Hello @fekir,

thanks for reporting this issue. The current implementation did consider only the case that the static variable gets initialized by a constructor but not by a `CallExpr`.

A fix is on its way.

Andreas

**Comment by fekir** [comment]
Wow, what a fast fix.

I've done a couple test more, also with `noexcept` and `throw()` functions. Seems all fine.


I'm just uncertain about if difference for those cases is intended and/or correct:


````
struct foo{
  constexpr foo() noexcept {};
};


const foo& create(){
	static foo value = foo();
  	return value;
}
````


````
struct foo{
  foo() = default;
};


const foo& create(){
	static foo value = foo();
  	return value;
}
````


Also adding a lambda with a simple return statement seems a big pessimization .
Again, not 100% sure if intended, as normally the compiler (at least gcc without optimisations) sees that the lambda cannot throw:

````
struct foo{
  foo() noexcept;
};


const foo& create(){
	static foo value = [](){return foo();}(); // adds exception handling
  	return value;
}
````
vs
````
struct foo{
  foo() noexcept;
};


const foo& create(){
	static foo value = foo(); // exception handling missing
  	return value;
}
````


Thank you very much!

**Comment by andreasfertig** [comment]
Hello @fekir,

> Wow, what a fast fix.

you're welcome.

> I've done a couple test more, also with noexcept and throw() functions. Seems all fine.

Great! It is always great if someone double checks what I'm doing here :-)

> I'm just uncertain about if difference for those cases is intended and/or correct:

Let me first say that the entire `static` transformation is hand-crafted. It happens in the back-end and not in the front-end. C++ Insights uses the front-end result. That difference may not be obvious to everybody.

That said, I can only try to provide my view, that is not me saying I'm right. Feel free to point me to the places where my view seems to be incorrect. l looked at your examples.

For the first pair I have a fix. The second one leave me puzzled. I have no clue on what that optimization is based. The lambdas call operator isn't `noexcept` and by that can in theory throw. However, the compiler seems to see a way to optimize this away. I have to look what Clang is doing there for its CodeGen.

Thanks again for reviewing this!

Andreas

**Comment by fekir** [comment]
> For the first pair I have a fix. The second one leave me puzzled. I have no clue on what that optimization is based. The lambdas call operator isn't noexcept and by that can in theory throw. However, the compiler seems to see a way to optimize this away. I have to look what Clang is doing there for its CodeGen.

I thought that lambda would be "deduced" noexcept, but it does not seem to come from the standard.
My guess was that as it is defined locally, the compiler uses that information (inlining even ith -O0 maybe?), but i have no insights (for that I use your tool :-P) how it is done...

It is actually an additional nice example on how lambdas are not just syntactic sugar/how much they provide for free.

What just popped my mind is that it could be related RVO... in cppinsight the value is initialized with ``new (&__value) foo(std::move(__lambda_7_21.operator()()));`, so it seems the move constructor is called.


I also noticed that changing

````
struct foo{
  foo() noexcept;
};

const foo& create(){
	static foo value = [](){return foo();}(); // adds exception handling
  	return value;
}
````

to 
````
struct foo{
  foo() noexcept;
};

const foo& create(){
	static foo value { [](){return foo();}()}; // does not add exception handling
  	return value;
}
````

removes the exception handling.

**Comment by andreasfertig** [comment]
Hello @fekir 

> I thought that lambda would be "deduced" noexcept, but it does not seem to come from the standard.
> My guess was that as it is defined locally, the compiler uses that information (inlining even ith -O0 maybe?), but i have no insights (for that I use your tool :-P) how it is done...

Indeed, showing these things is the purpose of C++ Insights. The hazel here is that we are looking at stuff that happens in the back-end and seems to depend on optimizations. It looks like the different compilers do different things at `-O0`: [https://godbolt.org/z/5fqcq7](https://godbolt.org/z/5fqcq7) While you can see the try-catch in Clang, GCC seems to optimize it away even with `-O0`. I will leave the implementation as it is.

> It is actually an additional nice example on how lambdas are not just syntactic sugar/how much they provide for free.

Not this time: [https://godbolt.org/z/GTbYPo](https://godbolt.org/z/GTbYPo) It is the visibility of the call-operator which allows it to be inline. What surprises me is that as soon as I add a `throw` in the call-operator, GCC start to generate more code than Clang [https://godbolt.org/z/a93W8h](https://godbolt.org/z/a93W8h), but maybe the instructions are more efficient.

> What just popped my mind is that it could be related RVO... in cppinsight the value is initialized with ``new (&__value) foo(std::move(__lambda_7_21.operator()()));`, so it seems the move constructor is called.

The move here is a lie. The compiler is even better: [https://godbolt.org/z/MvjqnT](https://godbolt.org/z/MvjqnT).

To your second example, did I mention that this is all hand-written? In the last case, there is an `InitListExpr` formed by the curly braces. I'm not sure I do like to proceed with fixing this. The next step would be calling a function template or something. I welcome a patch, but I'm not sure if it is worth the effort to perfect this transformation.

Andreas

**Comment by fekir** [comment]
> It looks like the different compilers do different things at -O0

Oh, should have checked clang to.
I think that what is currently shown is better than removing the exception handling for the lambda, as it should not be taken for granted.

> The move here is a lie. 

I know it is, I thought that cppinsights believed there was a move (that could fail) and therefore the necessity to add exception handling code.

> I'm not sure if it is worth the effort to perfect this transformation
Agreed

I fear a patch is out of my reach, but I might give a look at it.
