### ISSUE TITLE
Lambda capture in a member function

### ISSUE THREAD

**Issue by tiberiu-maran** [andreasfertig/cppinsights#379]
Hi, I was playing around with this very neat tool, and I stumbled upon a scenario where it doesn't seem to produce the right result.

https://cppinsights.io/s/bb1d1c12

Basically the code should capture both the local variable `a` and a pointer to `this`, but in the generated code, even though `a` is declared it is not initialized by the constructor of the lambda structure.

**Comment by andreasfertig** [comment]
Hello @tiberiu-maran,

thanks for reporting this issue! Seems that this was sleeping for a long time. A fix is on its way.

Andreas
