### ISSUE TITLE
Incorrect code generation for IIFE inside if without parentheses

### ISSUE THREAD

**Issue by TerensTare** [andreasfertig/cppinsights#386]
First of all, I want to thank you for making CppInsights, it is a great and handy tool.
Then, consider the following C++20 code:
```cpp
#include <utility>

namespace tnt
{
    // vector
    template <typename T, std::size_t N>
    struct vector final
    {
      static_assert(N > 0);
      
        template <typename U, std::size_t S>
        constexpr vector& operator=(vector<U, S> &&rhs) noexcept
        {
            if (this != &rhs)
                [this, rhs = std::move(rhs)]
                    <std::size_t... I>(std::index_sequence<I...>) noexcept {
                    ((data[I] = std::exchange(rhs.data[I], U(0))), ...);
                }(std::make_index_sequence<S>{});
            return *this;
        }

    private:
        T data[N]{};
    };
} // namespace tnt

int main()
{
}
```
As it can be seen from the generated code of the move assignment operator, the lambda is generated inside the if clause, and then called outside the if. The part from the generated lambda-class body and after the invocation of the lambda should be inside the if (surrounded by `{` and `}`).

**Comment by andreasfertig** [comment]
Hello @andreasfertig,

my pleasure! Thanks for reporting this. It took a bit longer than usual because this issue is not just present with `if`. It is wrong for `while`, `do ... while`, and `for` as well. As a bonus, the example above revealed that `final`was inserted at the wrong position. So you reported two bugs at once :-) A fix is on its way.

Andreas

**Comment by TerensTare** [comment]
My pleasure to be of help! As for for the `final`, I have noticed it but I thought this was the intended behaviour😅.
Thank you once again,

Terens

**Comment by andreasfertig** [comment]
Every bug counts! :-)
