### ISSUE TITLE
Can insights show the relationship info between source's lines and the output's line?

### ISSUE THREAD

**Issue by fang13** [andreasfertig/cppinsights#393]
Can insights show the relationship info between source's lines and the output's line?

**Comment by andreasfertig** [comment]
Hello @fang13,

at the moment, it cannot. Some time ago, I looked into a way of attributing the output with its source lines. I found that this approach might work on a function of class scope, but it gets more difficult when it gets down to something like a lambda or, say, correlating a template instantiation with its source.

If you see a way to do it and patch the web-frontend, I'm happy about a patch.

Andreas

**Comment by fang13** [comment]
Thanks for your answer. I will try another way to look for their reloationship. 

Best wishes.

**Comment by andreasfertig** [comment]
Hello @fang13,

this issue has been open for some time now. I'll close it in a couple of days if nobody objects and presents a solution.

Andreas
