### ISSUE TITLE
error: variable-sized object may not be initialized

### ISSUE THREAD

**Issue by jetcoder** [andreasfertig/cppinsights#394]
Full error message:
```
/home/insights/insights.cpp:8:10: error: variable-sized object may not be initialized
        int arr[num] {};
                ^~~
1 error generated.
Error while processing /home/insights/insights.cpp.
```
During following code running:
```
#include <iostream>

int main()
{
	int num;
	std::cin >> num;	
	
	int arr[num] {};
	
	for (auto& item : arr)
	{
		std::cout << item << " ";
	}
	std::cout << std::endl;
		
}
```
The error is shown for C++ standards from 11 to 20a.

**Comment by i-ky** [comment]
As far as I know, variable length array is not a part of C++ standard, it is a [GCC extension](https://gcc.gnu.org/onlinedocs/gcc/Variable-Length.html). To an extent, clang supports VLA too, but it does not support initialization of such arrays.

**Comment by jetcoder** [comment]
There is ans example in C++14 standard (N3690):
§ 8.3.4
```
void f(unsigned int n) {
    int a[n]; // type of a is “array of runtime bound of int”
}
```
But indeed, looks like clang doesn't support VLAs.

**Comment by andreasfertig** [comment]
Hello @jetcoder,

VLA's are special. They work, even in Clang, if you remove the braced-init. As the size of a VLA is unknown at compile-time, the compiler cannot produce an initializer for it at compile-time. Hence, the following works:

```c++
int num;
std::cin >> num;	
	
int arr[num];
```

As this is not a C++ Insights bug, I'm closing this issue.

Andreas
