### ISSUE TITLE
Incorrectly interprets C cast as static_cast instead of reinterpret_cast

### ISSUE THREAD

**Issue by leg0** [andreasfertig/cppinsights#398]
This code is doing a reinterpret_cast, but cppinsights says it's doing a static_cast.
in:
```C++
void f()
{
  int* p = (int*)5;
}
```

out:
```C++
void f()
{
  int * p = static_cast<int *>((5));
}
```

**Comment by andreasfertig** [comment]
Hello @leg0,

thanks for reporting this! A fix is on its way.

Andreas
