### ISSUE TITLE
Bugged output for namespace variable declaration

### ISSUE THREAD

**Issue by jeremy-rifkin** [andreasfertig/cppinsights#408]
The following program

```cpp
namespace ns {
    extern int a;
};

int ns::a = 1;
```

Produces this output on cppinsights:

```cpp
namespace ns
{
  extern int a;

}

int a = 1;
```

The output should be along the lines of:

```cpp
namespace ns {
  extern int a;
}

namespace ns {
  int a = 1;
}
```

**Comment by andreasfertig** [comment]
Hello @jeremy-rifkin,

thanks for spotting this! Last week I realized that the scope was dropped for static data members but I did not think about a variable in a namespace. A fix is on its way.

Andreas
