### ISSUE TITLE
Segmentation fault when using polymorphic lambdas

### ISSUE THREAD

**Issue by cpp-red-lion** [andreasfertig/cppinsights#41]
Hi,

See sample code:

[Sample](https://cppinsights.io/lnk?code=I2luY2x1ZGUgPHZlY3Rvcj4KI2luY2x1ZGUgPGFsZ29yaXRobT4KI2luY2x1ZGUgPHN0cmluZz4KCnVzaW5nIG5hbWVzcGFjZSBzdGQ7CgppbnQgbWFpbigpCnsKICB2ZWN0b3I8c3RyaW5nPiB2ID0geyAiYWFhIiwgImJiYiIsICJjY2MiIH07CiAgCiAgYXV0byBpdCA9IHN0ZDo6ZmluZF9pZihiZWdpbih2KSwgZW5kKHYpLCAKICAgICAgICAgICAgICAgICAgICAgICAgIFtdKGNvbnN0IGF1dG8gJiBzdHIpeyByZXR1cm4gc3RyID09ICJiYmIiO30gKTsKfQ==&rev=1.0)

When replacing `const auto & str` with `const string & str` it works.

**Comment by andreasfertig** [comment]
Hi Victor,

congratulations this is the first official crash report!!! :-)

I aim to release a major update today. After that I will add the fix to this issue (typical nullptr problem :-()
