### ISSUE TITLE
Feature request: show substitution failures

### ISSUE THREAD

**Issue by eyalroz** [andreasfertig/cppinsights#423]
It would be nice if cppinsights could print what items in an overload set were rejected due to substitution failure (for illustrating how SFINAE constructs work).

**Comment by andreasfertig** [comment]
Hello @eyalroz,

interesting idea. I don' know whether that is possible.

Let's assume it would be possible. How would you like them to be presented? What makes template errors so annoying is the compiler telling us all the overloads it tried. 


Best,

   Andreas

**Comment by eyalroz** [comment]
Well, initially, and assuming this would possible, I would just like the signatures of the overload-set members for which substitution failed, without listing the failure reason. Remember that the annoying long warning messages are mostly due to showing the entire instantiation "stack" down to where the actual failure occurred. If you only show the outer-level, it should be less painful to go through. But it would be quite useful for debugging template programming issues! Plus, it's part of how your project presents itself: "the magic the compiler does for us to make things work." - sometimes the magic can get somewhat verbose.

**Comment by eyalroz** [comment]
That doesn't seem fair.

**Comment by andreasfertig** [comment]
Hello @eyalroz,

yes, sorry I forgot to remove the tag.

Anyhow, so far I haven't found a way getting this overload set.

Andreas
