### ISSUE TITLE
Compiler Generated Destructor

### ISSUE THREAD

**Issue by ochavan9** [andreasfertig/cppinsights#430]
Hi,
Firstly, great job with this tool. It really helps to understand what magic the compiler does with our source code, especially providing insights about the modern cpp features.
I was trying out the tool for below code snippet:
class A{};
int main(){	
A a;
} 
The compiler output:
class A
{
  public: 
  // inline constexpr A() noexcept = default;
};
int main()
{
  A a = A();
}

Here for the class A compiler generated a default constructor. But I don't see a destructor generated. When object 'a' goes out of scope the destructor should be called. But I don't see it in the compiler output of the tool.
Please correct me if I missed anything

**Comment by andreasfertig** [comment]
Hello @ochavan9,

thank you!

Well, that is hard to understand. Clang sees that no destructor is necessary for your code example and hence doesn't bother generating one. You can see this independently from C++ Insights in Compiler Explorer [godbolt.org/z/n8hWY7KbK](https://godbolt.org/z/n8hWY7KbK):

```
Destructor simple irrelevant trivial constexpr needs_implicit
```

This changes once you add a data member which requires destruction, for example [cppinsights.io/s/22d2c9e4](https://cppinsights.io/s/22d2c9e4):

```C++
class D {
public:
  ~D() {}
};

class A{
  D d;
};

int main(){
  A a;
}

```

I hope this helps.


Andreas

**Comment by ochavan9** [comment]
So, is this a clang specific optimization?
I also tried allocating on heap and invoking delete operator, but even then the destructor was not generated
```
class A{
};

int main(){
  A* a = new A;
  delete a;
}
```
So, unless you have a data member or derived part that requires destruction, the compiler does some optimization for trivial cases. Is that so?

**Comment by andreasfertig** [comment]
Hello @ochavan9,

sorry for the delay. I don't know whether it is Clang specific. However, if there is nothing to destruct, which is the case in an empty class or even a class with only builtin members, a destructor is just overhead.

Andreas
