### ISSUE TITLE
Remove MSVC warning D9025 `overriding '/MD' with '/MT'`

### ISSUE THREAD

**Issue by andreasfertig** [andreasfertig/cppinsights#443]
The Windows builds using `cl.exe`, for example "MSVC 2022 / LLVM 13 @ Windows Release" produce the warning `D9025`:

```
[1/12 0.1/sec] Building CXX object CMakeFiles\insights.dir\DPrint.cpp.obj
cl : Command line warning D9025 : overriding '/MD' with '/MT'
cl : Command line warning D9025 : overriding '/EHs' with '/EHs-'
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
cl : Command line warning D9025 : overriding '/GR' with '/GR-'
```

The full output can be found here [github.com/andreasfertig/cppinsights/runs/5076959142](https://github.com/andreasfertig/cppinsights/runs/5076959142?check_suite_focus=true#step:15:63)

The values `MT`, `EHs-`, ... are obtained from `llvm-config` [github.com/andreasfertig/cppinsights/runs/5076959142](https://github.com/andreasfertig/cppinsights/runs/5076959142?check_suite_focus=true#step:14:97):

```
-- llvm_config(LLVM_CXXFLAGS)=>/external:I D:\a\cppinsights\cppinsights\current\include    /EHs-c- /GR- -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -DUNICODE -D_UNICODE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS;
```

It looks likes `cmake` sets some kind of default (`MD`) which is not correctly overridden.

The values from `llvm_config` should be used for the build, other defaults should be removed.

Andreas

**Comment by jcelerier** [comment]
I think that for CMake you should use https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html to set it to match what llvm gives.

**Comment by andreasfertig** [comment]
Hello @jcelerier,

thanks! How do I use these generator expressions? Like that:

```
set_property(TARGET insights PROPERTY
  MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")

set_property(TARGET insights PROPERTY
  MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Releae>:Release>")
```

Setting both properties and `cmake` decides which one to use? Does this property also control `EHs`?


Andreas

**Comment by jcelerier** [comment]
The flags are 

     MultiThreaded -> MT
     MultiThreadedDebug -> MTd
     
  so 

    MultiThreaded$<$<CONFIG:Debug>:Debug>

will evaluate to MultiThreadedDebug if CMAKE_BUILD_TYPE=Debug and MultiThreaded in all the other cases. But I think that you should just set it to whatever llvm-config gives you because it's the one which is imposing it (you need to link with a CMAKE_BUILD_TYPE=Debug llvm if your own app is on debug mode and a CMAKE_BUILD_TYPE=Release llvm on release mode because the ABI of std:: and of some LLVM types do change anyways)

**Comment by jcelerier** [comment]
(my personal solution to sidestep this madness is to not use MSVC at all but Clang+libc++ on Windows which does not have these issues - a debug libc++ can be used by programs built in Release and conversely)

**Comment by andreasfertig** [comment]
Thanks!

C++ Insights uses both, Clang+libc++ on Windows and cl.exe + libc++. Mainly to get all errors and warnings and ensure that this setup works as well.

I see how to approach this. Thank you for your support!
