### ISSUE TITLE
For loops

### ISSUE THREAD

**Issue by pepsiman** [andreasfertig/cppinsights#45]
https://en.cppreference.com/w/cpp/language/for says that for loops are equivalent to while loops.

"The above syntax produces code equivalent to:

{
init_statement 
while ( condition ) { 
statement 
iteration_expression ; 
}
}"

**Comment by pepsiman** [comment]
I was thinking that there's a sequence of transforms, and the user chooses where to stop.
Range based for -> for -> while -> if and goto.

**Comment by simonrenger** [comment]
Conceptual idea:
Maybe add an extra mode in there like in a way that the user can choose between how deep cppinsight shall go/ transform

**Comment by andreasfertig** [comment]
Hello @simonrenger,

extra mode like a command line option: -use-while-loops?

Andreas

**Comment by simonrenger** [comment]
@andreasfertig  yes in that way and on the website than just a drop down menu or checkbox(s). I am sure there are other things than just while loops

**Comment by andreasfertig** [comment]
Hello @simonrenger, @pepsiman,

ok that is what I have in mind. I will push a patch to introduce this functionality in C++ Insights. There will be options to C++ Insights `-alt-syntax-for` and one for #44. However, it will take some additional time to prepare the website with a drop down menu with checkbox(s). As web-dev is not my strong suite, contributions for the drop down checkbox menu are welcome.

Andreas
