### ISSUE TITLE
noexcept for member functions not generating try...catch

### ISSUE THREAD

**Issue by andijcr** [andreasfertig/cppinsights#454]
[example](https://cppinsights.io/lnk?code=c3RydWN0IERhdGEKewogIGludCBpOwogIGRvdWJsZSBkOwogIGRvdWJsZSBmdW5jKCkgY29uc3Qgbm9leGNlcHR7CgkvLyBzaG91bGQndCBhbHNvIHRoaXMgc2hvdyBhIHRyeSAuLi4gY2F0Y2ggYmxvY2s/IAogICAgcmV0dXJuIGQqaTsKICB9Cn07CgoKaW50IGZ1bmMoKSBub2V4Y2VwdCB7CiAgcmV0dXJuIDQqNjsKfQoKCg==&insightsOptions=cpp20,all-implicit-casts,edu-show-noexcept&std=cpp20&rev=1.0)

shouldn't noexcept on a member function generate the same implicit try ... catch block, as it happens for a free function, or it's just a case of clang not doing it?

**Comment by andreasfertig** [comment]
Hello @andijcr,

thanks for reporting this. My apologies. This is a bug in my implementation. I left the member function case out. A fix is on its way.

Andreas
