### ISSUE TITLE
overloading operator new and operator delete

### ISSUE THREAD

**Issue by venkat-gvk** [andreasfertig/cppinsights#455]
Shouldn't the generated output prefix the keyword 'static' in member function as operator new and delete functions are static by default?

[operator new and delete](https://cppinsights.io/s/3780d1db)

**Comment by andreasfertig** [comment]
Hello @venkat-gvk,

thanks for bringing this up! I believe what C++ Insights shows is correct. We can have both a `static` and non-static version. It is up to us to say when the operator should be `static`. See [cppreference.com/w/cpp/memory/new/operator_new](https://en.cppreference.com/w/cpp/memory/new/operator_new)

> ... Both single-object and array allocation functions may be defined as public static member functions of a class (versions (15-18)). ...


Andreas

**Comment by andreasfertig** [comment]
Hello @venkat-gvk,

my appologies but my initial answer was wrong. You're right, the overloaded operators new and delete are implicitly static. Here is the correct source: [[class.free]](https://eel.is/c++draft/class.free#1)

A fix is on its way.

Andreas
