### ISSUE TITLE
alignas(xxx) is repeated 

### ISSUE THREAD

**Issue by nickhuang99** [andreasfertig/cppinsights#456]
Taking _tests/AlignAsTest.cpp_ as an example, the expression "alignas(128)" is **repeated** because it is **not** treated as part of global variable. To me, alignas is more or less like a sort of "assert" statement. Therefore "GetSourceRangeAfterSemi" does NOT include "alignas(128)" at all.  

issue description:   
original:   **alignas(128)** char alignedArray[128];
transformed:   **alignas(128)** **alignas(128)** char alignedArray[128];

_suggested fix_:
<pre><code>
diff --git a/GlobalVariableHandler.cpp b/GlobalVariableHandler.cpp
index 6d3547b..49823f8 100644
--- a/GlobalVariableHandler.cpp
+++ b/GlobalVariableHandler.cpp
@@ -94,7 +94,7 @@ void GlobalVariableHandler::run(const MatchFinder::MatchResult& result)
                                  outputFormatHelper.GetString());
 
         } else {
-            mRewrite.ReplaceText(sr, outputFormatHelper.GetString());
+            //mRewrite.ReplaceText(sr, outputFormatHelper.GetString());
         }
     }
 }
</code></pre>

**Comment by andreasfertig** [comment]
Hello @nickhuang99,

thanks for spotting and reporting this. A fix is on its way.

Andreas
