### ISSUE TITLE
convert ‘bool’ to ‘clang::TemplateName::Qualified’not allowed in latest GCC

### ISSUE THREAD

**Issue by nickhuang99** [andreasfertig/cppinsights#458]
When compiling with latest GCC-11.2.0 with -std=c++20, there is error like _convert ‘bool’ to ‘clang::TemplateName::Qualified’_ error
 It is better just leave it for default.

<pre><code>
diff --git a/InsightsHelpers.cpp b/InsightsHelpers.cpp
index d08157f..da68e0e 100644
--- a/InsightsHelpers.cpp
+++ b/InsightsHelpers.cpp
@@ -1378,7 +1378,8 @@ void StringStream::Print(const TemplateArgument& arg)
 
 void StringStream::Print(const TemplateSpecializationType& arg)
 {
-    arg.getTemplateName().print(*this, CppInsightsPrintingPolicy{}, true);
+    //arg.getTemplateName().print(*this, CppInsightsPrintingPolicy{}, true);
+       arg.getTemplateName().print(*this, CppInsightsPrintingPolicy{});
 }
 //-----------------------------------------------------------------------------
 

</code></pre>

**Comment by mingodad** [comment]
With clang14 I'm getting the same error and applying the fix shown above has allowed I was able to build.

**Comment by andreasfertig** [comment]
Hello @nickhuang99,

thanks for the fix. I use a modified version.

Andreas

**Comment by nickhuang99** [comment]
Can you merge the fix to main branch?

Sent via the Samsung Galaxy S22 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
