### ISSUE TITLE
Expansion of global lambda expressions is broken

### ISSUE THREAD

**Issue by neobrain** [andreasfertig/cppinsights#46]
Lambda expressions at global scope generate unintelligible output. C++ Insights is supposed to replace them with equivalent, explicit class definitions, but this only seems to work properly for lambda expressions defined inside a function.

The following table illustrates the output for a locally defined lambda (fine) vs. two instances of global lambdas (broken).

<table>
<tr>
<th>
Input
</th>
<th>
C++ Insights
</th>
</tr>
<tr>
<td  valign="top">
<pre lang="cpp">
int main() {
    auto x = [a=5](int b) {
        return b*a;
    };
}</pre>
</td>
<td  valign="top">
<pre lang="cpp">
int main() {
  class __lambda_10_14 {
    public: inline /*constexpr */ int operator()(int b) const {
      return b * a;
    }

&nbsp;&nbsp;&nbsp;&nbsp;private:
&nbsp;&nbsp;&nbsp;&nbsp;int a;
    
&nbsp;&nbsp;&nbsp;&nbsp;public:
&nbsp;&nbsp;&nbsp;&nbsp;__lambda_10_14(int _a)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: a{_a}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{}
&nbsp;&nbsp;};
  
&nbsp;__lambda_10_14 x = __lambda_10_14{5};
}
</pre>
</td>
</tr>
<tr>
<td  valign="top">
<pre lang="cpp">
auto x = []() {
    return 5;
};
</pre>
</td>
<td  valign="top">
<pre lang="cpp">
__lambda_1_10 x = /* public: inline ~() noexcept; */
static inline int __invoke();
         ;
</pre>
</td>
</tr>
</tr>
<tr>
<td  valign="top">
<pre lang="cpp">
auto x2 = [a=5](int b) {
    return b*a;
};
</pre>
</td>
<td  valign="top">
<pre lang="cpp">

__lambda_5_11 x2 = /* public: inline ~() noexcept; */
[inta=5](int binline constexpr int operator()(int b) const
                     {
                       return b * a;
                     }
                     ;
</pre>
</td>
</tr>
</tr>
</table>

**Comment by andreasfertig** [comment]
Hi Tony,

thanks for reporting that with Tony-Tables :-) Surprisingly I have no test for a global Lambda.

The AST matchers are still a source of trouble. Next step is matching the whole TU. But that will take some time.

However, patch is on its way.

**Comment by neobrain** [comment]
Happy to help, thanks for the quick fix :)
