### ISSUE TITLE
error: unknown argument: '-mno-sched-prolog'

### ISSUE THREAD

**Issue by fang13** [andreasfertig/cppinsights#464]
when i use insights to parse a cpp file，some errors happen like 
error: unknown argument: '-mno-sched-prolog'
error: unknown argument: '-fno-partial-inlining'

(The compiler in compile_command.json is 'arm-linux-gnueabi-g++')

how to solve this question?

**Comment by andreasfertig** [comment]
Hello @fang13,

`arm-linux-gnueabi-g++` sounds to me like this json file was produced with a g++ compiler? If so, then I guess there are command line options which Clang doesn't understand. The fix would be deleting them from the json file.

Andreas
