### ISSUE TITLE
static inside lambda results in incorrect code

### ISSUE THREAD

**Issue by JJCUBER** [andreasfertig/cppinsights#467]
The code
```cpp
#include <iostream>

int main()
{
    auto l = []()
    {
      static int n{};
      std::cout << ++n;
    };
  
}
```
generates code with two separate functions with the same static variable declared twice
```cpp
#include <iostream>

int main()
{
    
  class __lambda_5_11
  {
    public: 
    inline void operator()() const
    {
      static int n = {};
      std::cout.operator<<(++n);
    }
    
    using retType_5_11 = void (*)();
    inline /*constexpr */ operator retType_5_11 () const noexcept
    {
      return __invoke;
    };
    
    private: 
    static inline void __invoke()
    {
      static int n = {};
      std::cout.operator<<(++n);
    }
    
    
    public:
    // /*constexpr */ __lambda_5_11() = default;
    
  };
  
  __lambda_5_11 l = __lambda_5_11{};
  return 0;
}
```
If one were to run the generated code with some direct calls of the lambda and some calls of it through a function pointer, it would result in incorrect results.

For example, you would get `123412` if you called it 4 times directly and then 2 times through a function pointer when using the generated code from cppinsights (whereas the original lambda would print `123456`):
```cpp
  l();
  l();
  l();
  l();
  (+l)();
  (+l)();
```

**Comment by andreasfertig** [comment]
Hello @JJCUBER,

I moved the second (and third issue) to a new issue to be able to track and fix them independently. They are not related, especially the `decltype` case is very special :-)

Regarding 

> Also, explicit template specializations reference lambda classes outside of scope, as cppinsights typically declares and defines them within the caller's scope, though that might just be a limitation of how cppinsights works?

That one is a bit tricky. Here is what I know. Lambdas are declared at the most narrow scope, i.e., inside `main` in your example. However, as this is a process done by the compiler, the resulting template specialization knows and can access this type. Despite that, the resulting transformation from C++ Insights produces code that does not compile. The first part of your issue reports seems down the same alley. The `invoke` functions seem to be also a bit more compiler-land than I like it to be :-)

Andreas
