### ISSUE TITLE
[C++20] Coroutine header file requires -fcoroutines

### ISSUE THREAD

**Issue by matrixjoeq** [andreasfertig/cppinsights#469]
<coroutine> header file cannot be included for C++20 features. It reports the following error:
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/coroutine:334:2: error: "the coroutine header requires -fcoroutines"
#error "the coroutine header requires -fcoroutines"

**Comment by andreasfertig** [comment]
Hello @matrixjoeq,

thanks for reporting this. You need to enable "Use libc++". Clang and GCC are not compatible at the moment.

Andreas

**Comment by andreasfertig** [comment]
Fixed by #514.
