### ISSUE TITLE
[C++20] format header file is not found

### ISSUE THREAD

**Issue by matrixjoeq** [andreasfertig/cppinsights#470]
When building source code with C++20 standard, the <format> header file introduced in C++20 standard is not found with following error:
/home/insights/insights.cpp:139:12: fatal error: 'format' file not found
  #include <format>

**Comment by andreasfertig** [comment]
Hello @matrixjoeq,

thanks for reporting this. At the moment the standard libraries from both GCC and Clang don't have this header in the version C++ Insights uses.

Andreas
