### ISSUE TITLE
Odd output for decltype return values. Lambda hunt.

### ISSUE THREAD

**Issue by olafurw** [andreasfertig/cppinsights#490]
Found two things that stood out as odd.

**Case A**

```
auto foo() -> decltype([](){ return 4; });
```

This defines a lambda class but then uses it like this

```
__lambda_5_24 foo();
() -> decltype([](){ return 4; });
```

Which does not seem like correct C++

![image](https://user-images.githubusercontent.com/103783/180744187-9455497d-cb00-463b-b63f-27db20f46312.png)

**Case B**

```
using x = decltype([](){ return 4; });
auto foo() -> x;
```

Which should be the same as Case A but the output does seem more correct but it does not define a lambda class.

```
using x = decltype([](){ return 4; });
__lambda_19_20 foo();
```

![image](https://user-images.githubusercontent.com/103783/180744371-402b9128-62c5-4151-9f38-156e7c9dd9be.png)

Insights link.
https://cppinsights.io/s/51754024

**Comment by andreasfertig** [comment]
Hello @olafurw,

thanks for reporting this. A fix is on its way.

Andreas
