### ISSUE TITLE
Reference collapsing works wrong

### ISSUE THREAD

**Issue by adromanov** [andreasfertig/cppinsights#50]
For the following piece of code:
```
template <class T>
void foo(T && t)
{ }

struct Test {};

int main()
{
    Test test;
    foo(test);
    return 0;
}
```
output of an instantiation of ``foo`` is the following:
```
/* First instantiated from: insights.cpp:10 */
#ifdef INSIGHTS_USE_TEMPLATE
template<>
void foo<Test &>(Test && t)
{
}
#endif
```
Argument type should be ``Test &`` but not ``Test &&`` because of reference collapsing.

**Comment by adromanov** [comment]
I've made some investigation on a following snippet:
```
template <class T>
void foo(T && t)
{ }

int main()
{
    int test = 0; 
    foo(test);
    return 0;
}
```
When insights process this parameter it eventually calls
```
static const std::string GetAsCPPStyleString(const QualType& t);
```
Actually, at this point ``t->getTypeClass()`` is ``Type::LValueReference`` and ``t->isLValueReferenceType()`` is **true**.
The reason that ``t.getAsString(..)`` returns ``int &&`` is how clang implements
```
// File is llvm/tools/clang/lib/AST/TypePrinter.cpp 
void TypePrinter::print(const Type *T, Qualifiers Quals, raw_ostream &OS, StringRef PlaceHolder);
```
Simplified call graph looks like:
```
TypePrinter::print()
├─printBefore()
│ └─printLValueReferenceBefore()
│   ├─printBefore() // <- getPointeeTypeAsWritten = SubstTemplateTypeParmType
│   │ └─printSubstTemplateTypeParmBefore()
│   │   └─printBefore() // <- getReplacementType = LValueRefeferenceType
│   │     └─printLValueReferenceBefore()
│   │       ├─printBefore() // <- getPointeeTypeAsWritten = BuiltinType                                                                                    
│   │       │ └─printBuiltinBefore()
│   │       │   └─OS << T->getName();
│   │       └─OS << "&";
│   └─OS << "&";
├─...
└─printAfter()
  └─printLValueReferenceAfter()
    └─printAfter() // <- getPointeeTypeAsWritten = SubstTemplateTypeParmType
      └─printSubstTemplateTypeParmAfter()
        └─printAfter() // <- getReplacementType = LValueRefeferenceType
          └─printLValueReferenceAfter()
            └─printAfter() // <- getPointeeTypeAsWritten = BuiltinType
              └─printBuiltinAfter()
                └─// do nothing
```

So, clang itself produces 2 ampersands for lvalues. Looks like a bug in clang for me, but 'm not sure.
Anyway, I guess this issue could be solved at **insights** level with some workaround.

P.S.: tested on llvm-6.0.1

**Comment by andreasfertig** [comment]
Hello adromanov,

thanks for nailing it down. It sure looks like a bug in clang. And I agree, it can be workaround in insights. I already have an idea, but this issue did draw my attention more to templates. Currently I'm looking into more than just this issue. There are a couple of other things which are incorrect. As soon as I have all together I will push a (temporary) fix. 
Do you know how to open a bug report to clang? Because, I would prefer them to fix it.

**Comment by adromanov** [comment]
> Do you know how to open a bug report to clang? Because, I would prefer them to fix it.
I'll try to report in a couple of days.

**Comment by adromanov** [comment]
That workaround doesn't work with:
```
template <class F>
void foo(F && f)
{ }

using F = int && (int &&);                                                                                                                                                                                         

int && f(int && i)
{
    return static_cast<int &&>(i);
}

int main()
{
    F & rf = f;
    foo(rf);
    return 0;
}
```
Top level && should be replaced with &, not the first one. This is tricky when we have only string representation of a type.

**Comment by adromanov** [comment]
Reported https://bugs.llvm.org/show_bug.cgi?id=38363

**Comment by andreasfertig** [comment]
Thanks! I'm curious what they say. I will revert the not so well working patch.

**Comment by adromanov** [comment]
Please, remove double ampersand hack from ``static const std::string GetAsCPPStyleString(const QualType& t)``:
1) it doesn't work properly
2) With new LLVM 7.0.0 there is no need in it - everything works fine, ``&`` is printed instead of ``&&``

Thanks!

**Comment by andreasfertig** [comment]
Hello adromanov,

I just reverted the hack. However, I could not confirm that it is fixed in my clang 7.0.0 version. That could be as it is a couple days if not weeks old. Also it will not show up in the web-frontend as Travis CI does not support the new llvm 7 repository yet. At least not easily.

**Comment by adromanov** [comment]
I've built a fresh 7.0.0 yesterday (tags/RELEASE_700/final) - it works for me.

**Comment by andreasfertig** [comment]
Hello adromanov,

I finally updated to Clang 7.0. As far as I can see this issue is be solved now.
