### ISSUE TITLE
Declaration of multiple variables is handled incorrectly

### ISSUE THREAD

**Issue by leg0** [andreasfertig/cppinsights#500]
Input:
```c++
int a,b,c;
```

Output:
```c++
int c;
```

Expecting to see all variable declarations in the output.

**Comment by andreasfertig** [comment]
Hello @leg0,

thanks for reporting this! That's an issue in global scope only. The three variables all have the same source location. Hence there are three rewrites for the same location. As a result, only the last rewrite survives. I'm unsure how to fix this without tracking the variables, which I'm not particularly eager to do. I plan to switch to a transformation at the TU level, which would solve this issue automatically. What I'm trying to say is that it can take a while until I fix this issue.

Andreas
