### ISSUE TITLE
 Please guide the complete installation process in ubuntu

### ISSUE THREAD

**Issue by Sharath8598** [andreasfertig/cppinsights#503]
Can you please guide the complete installation process in ubuntu. I am getting error after executing the ninja command .
![ninja](https://user-images.githubusercontent.com/112390552/187838761-387d7fb8-3f53-4711-867d-3d65eff63da8.PNG)

**Comment by Sharath8598** [comment]
Can you please guide the complete installation process in ubuntu. I am getting error after executing the ninja command

**Comment by andreasfertig** [comment]
Hello @Sharath8598,

I assume this was addressed by one of the other issues you opened related to compiling C++ Insights. Hence I'm closing the issue.

Andreas
