### ISSUE TITLE
Ninja command through error.

### ISSUE THREAD

**Issue by Sharath8598** [andreasfertig/cppinsights#504]
Please guide me how to install cpp insights. 

cc1plus: all warnings being treated as errors
ninja: build stopped: subcommand failed.
 
 I am getting error after run ninja command

**Comment by andreasfertig** [comment]
Hello @Sharath8598, 

I assume this was addressed by one of the other issues you opened related to compiling C++ Insights. Hence I'm closing the issue.

Andreas
