### ISSUE TITLE
printing output in html format!!

### ISSUE THREAD

**Issue by Sharath8598** [andreasfertig/cppinsights#505]
Is it possible to print the output in html or xml format.
if yes !! can you please guide me the procedure .

**Comment by andreasfertig** [comment]
Hello @Sharath8598,

I'm not sure whether I understand your question correctly. C++ Insights itself only does plain text output. Both HTML or XHTML are not supported. 

But maybe you're asking whether you can print a page on cppinsights.io? Then the answer is, sadly, no. But I would  accept a PR adding this functionality to the web front end.


Andreas

**Comment by Sharath8598** [comment]
Hi,
Hope you are doing well.............!! I would like to  know  which function is used to display the output in terminal. So I can please let me know that function? It is very important at this point of time so please help me out.

**Comment by andreasfertig** [comment]
Hello @Sharath8598,

I do, thanks!

C++ Insights uses [CodeMirror](https://codemirror.net/) for the syntax highlighting and HTML generation. If you want to get HTML formatted output from a local C++ Insights instance, you can also look at Python's codehilite.

Andreas

**Comment by Sharath8598** [comment]
Hi, good to know your doing well.
I  am running the cpp insights in ubuntu terminal(local machine), may I know which variable stores the cpp insights output or which function is displaying the output in the  terminal.  Because I want to know how to fetch the cpp insights output and send that output to another function(Please note that another  function told here refers to a user defined one).

**Comment by andreasfertig** [comment]
Hello @Sharath8598,

inside C++ Insights, the closest I can point you to is [Insights.cpp#L114](https://github.com/andreasfertig/cppinsights/blob/8a5173a23ec69afaf71b211f5046d45b6bbcd9fc/Insights.cpp#L114). The `mRewriter` contains all the rewrites and the original source.

Andreas
