### ISSUE TITLE
Incorrect naming in parameter pack expansion

### ISSUE THREAD

**Issue by pixeldexter** [andreasfertig/cppinsights#506]
https://cppinsights.io/s/5ced24b2

So, this code
   template<class...Match>
   bool search(char ch, Match&&...matchers) {
      return (matchers(ch) || ...);
   }
   search('A', ::isalpha, ::isdigit, []() { lambda });

gets insighted into
   bool search<... params...>(char ch, int (&matchers)(int) noexcept, int (&matchers)(int) noexcept, __lambda_12_50 && __matchers3) 

Notice how first and second parameters are named 'matchers', but the third parameter is named 'matchers3'. It looks like there is an internal counter, it is just being output for lambda and not for regular function argument.

**Comment by andreasfertig** [comment]
Hello @pixeldexter,

thanks for reporting this. You're right. There is a counter, the one Clang, assigned to each parameter. C++ Insights uses this counter is based on the query whether some parameter is part of a parameter pack. This function is here [InsightsHelpers.cpp](https://github.com/andreasfertig/cppinsights/blob/8a5173a23ec69afaf71b211f5046d45b6bbcd9fc/InsightsHelpers.cpp#L1230).

Now for the example you provided, the check says that it is only an RValue or LValue reference (depending on the parameters). There is no glue I could find that indicates that this parameter comes from a parameter pack.

That issue will remain unfixed unless someone can show me how to get this information.

Andreas
