### ISSUE TITLE
Wrong output for the initialization of static variables within a function

### ISSUE THREAD

**Issue by Redstone1024** [andreasfertig/cppinsights#507]
For the initialization of static variables within functions, based on comparison with assembly output and analysis, I believe that a call to `__cxa_atexit` should be included, otherwise the class object cannot be destructured on program exit.

The following references are used in the analysis process.

[C++ Insights](https://cppinsights.io/lnk?code=c3RydWN0IGV4YW1wbGVfc3RydWN0CnsKICAgIGV4YW1wbGVfc3RydWN0KCkgeyB0aHJvdzsgfQoJfmV4YW1wbGVfc3RydWN0KCkgeyB9Cn07CgpleGFtcGxlX3N0cnVjdCYgZ2V0X2V4YW1wbGUoKQp7CglzdGF0aWMgZXhhbXBsZV9zdHJ1Y3QgdGVtcDsKCXJldHVybiB0ZW1wOwp9Cg==&insightsOptions=cpp2b&std=cpp2b&rev=1.0)

[Compiler Explorer](https://godbolt.org/clientstate/eyJzZXNzaW9ucyI6W3siaWQiOjEsImxhbmd1YWdlIjoiYysrIiwic291cmNlIjoic3RydWN0IGV4YW1wbGVfc3RydWN0XG57XG4gICAgZXhhbXBsZV9zdHJ1Y3QoKSB7IHRocm93OyB9XG5cdH5leGFtcGxlX3N0cnVjdCgpIHsgfVxufTtcblxuZXhhbXBsZV9zdHJ1Y3QmIGdldF9leGFtcGxlKClcbntcblx0c3RhdGljIGV4YW1wbGVfc3RydWN0IHRlbXA7XG5cdHJldHVybiB0ZW1wO1xufVxuIiwiY29tcGlsZXJzIjpbeyJpZCI6ImdzbmFwc2hvdCIsIm9wdGlvbnMiOiItc3RkPWMrKzJiIn1dfV19)

This function call is missing.

```
mov     edx, OFFSET FLAT:__dso_handle
mov     esi, OFFSET FLAT:_ZZ11get_examplevE4temp
mov     edi, OFFSET FLAT:_ZN14example_structD1Ev
call    __cxa_atexit
```

Translated with DeepL.

**Comment by andreasfertig** [comment]
Hello @Redstone1024,

thanks for reporting this. As far as I can tell, you're right. The only thing is that `__cxa_atexit` requires parameters. C++ Insights doesn't show destructors as they are not part of the AST. I must figure out what I want to do in this special case. Of course, if you bring me a PR, I will most likely accept that :-)

Andreas

**Comment by Redstone1024** [comment]
Thanks for the reply, also `if(!__tempGuard)` should it be `if((__tempGuard & 0xff) == 0)` ? After all, here it should ensure that the initialization is complete, not continue the logic below while other threads are initializing.
