### ISSUE TITLE
insights crashed on some invalid inputs

### ISSUE THREAD

**Issue by adromanov** [andreasfertig/cppinsights#51]
Crashed on the following piece of code:
```
#include <map>

int main()
// no open curly bracket here
    using Map = std::map<int, bool>;
    Map m;
    auto [it, ok] = m.insert({1, true});
}
```
Output is:
```
/home/insights/insights.cpp:5:5: error: expected function body after function declarator
    using Map = std::map<int, bool>;
    ^
/home/insights/insights.cpp:6:4: error: unknown type name 'Map'
        Map m;
        ^
/home/insights/insights.cpp:8:1: error: extraneous closing brace ('}')
}
^
[0x129475a]
....
[0x4a4407]
Segmentation fault (core dumped)
```

Without line
```
auto [it, ok] = m.insert({1, true});
```
there is no crash, just errors reported.

**Comment by adromanov** [comment]
Your local machine is on OS X, right? My is on linux and I can see a crash locally. Latest llvm+clang built with gcc-8.1.0.

**Comment by andreasfertig** [comment]
Thanks for your spec. It's correct I use OS X. I will fire up a docker container and see what's happening there. There is a chance that it is a bug which is also reachable in a different (compiling) context.
