### ISSUE TITLE
[document] Vim plugin for cppinsights

### ISSUE THREAD

**Issue by Freed-Wu** [andreasfertig/cppinsights#516]
![screen-2023-02-21-15-12-25](https://user-images.githubusercontent.com/32936898/220273531-d183042e-50e5-4ddf-b782-866bae786e44.jpg)

I create a [vim plugin](https://github.com/Freed-Wu/cppinsights.vim) for this project. Can it be added to `README.md` of this project?

**Comment by andreasfertig** [comment]
Hello @Freed-Wu,

nice! Of course, your project can be listed in `README.md`. Feel free to create a PR, and I will merge it.


Andreas
