### ISSUE TITLE
Can I use #include <Windows.h> with cppinsights?

### ISSUE THREAD

**Issue by rajendrasp** [andreasfertig/cppinsights#535]
I am trying to do it and it is giving me error that 

'Windows.h' file not found

Is it possible to use this inclue file with cppinsights online tools?

**Comment by andreasfertig** [comment]
Hello @rajendrasp,

I'm sorry, but the online version of C++ Insights runs under Linux. Hence it has no Windows headers.

Andreas

**Comment by rajendrasp** [comment]
Oops.. how about if I build it locally? Will I be able to use it on Windows? Can I feed it 'Windows.h' in that case? And Can I feed it more than one file?

**Comment by andreasfertig** [comment]
Hello @rajendrasp,

a while ago, I lost the build bots for Windows. So in pure theory, C++ Insights should compile and run under Windows. Then you can include "Windows.h," but I think you still can feed only one file.

Andreas

**Comment by andreasfertig** [comment]
I'm closing this issue; there is #177, which is about Windows support but hasn't progressed for a long time.
