### ISSUE TITLE
invoke lambda with `temp.operator()()` generate wrong code.

### ISSUE THREAD

**Issue by heroboy** [andreasfertig/cppinsights#550]
Generally, it generate the code to `temp.operator __lambda_6_15::retType_6_15()`.
But in many cases, the generated lambda class doesn't contains `retType`.

As I tested:
```cpp

//this is correct
auto temp = []() {};
temp.operator()();
  
//wrong
auto temp2 = []<typename>() {};
temp2.operator()<int>();

//wrong
int v = 1;
auto temp3 = [v]() {};
temp3.operator()();


```

**Comment by andreasfertig** [comment]
Hello @heroboy,

thanks for spotting and reporting this issue! A fix is on its way.


Andreas
