### ISSUE TITLE
Specialization of variable templates misses type deduction and `template`

### ISSUE THREAD

**Issue by Ukilele** [andreasfertig/cppinsights#556]
The following code:
```cpp
template<class T> auto Value = 10;
template<> auto Value<char> = 0.0;
```
generates following output in cppinsights:
```cpp
template<class T>
int Value = 10;
<> auto Value<char> = 0.0;
```
There are two issues:
1. For both, the primary template and the specialization of `Value`, we use `auto`. But only in the primary template cppinsights replaces `auto` by `int`. But it would be nice if also for the specialization it would replace `auto` by the according type (`double`).
2. In line 3 of the output of cppinsights, it is missing the keyword `template` in front of the `<>`.

**Comment by andreasfertig** [comment]
Hello @Ukilele,

thanks for reporting this issue!

A fix is on its way.

Andreas
