### ISSUE TITLE
Pack expansion in ctor call transformed into invalid c++

### ISSUE THREAD

**Issue by denis-gerasimov** [andreasfertig/cppinsights#595]
Hi Andreas, thank you for the great tool.

Looks like 
`std::tuple<C...> tpl(c...);`
gets transformed into something odd:
`std::tuple<C...> tpl = c... ;`

Shouldn't the code stay the same in this case?

Here is the full example: https://cppinsights.io/s/c901a485

**Comment by andreasfertig** [comment]
Hello @denis-gerasimov,

thank you for spotting and reporting this issue! A fix is on its way.

Andreas
