### ISSUE TITLE
Add support for `SourceLocExpr`

### ISSUE THREAD

**Issue by Ukilele** [andreasfertig/cppinsights#598]
The following input:
```c++
auto X = __builtin_LINE();
```
generates following output:
```c++
unsigned int X = /* INSIGHTS-TODO: CodeGenerator.cpp:3851 stmt: SourceLocExpr */;
```
According to https://docs.hdoc.io/hdoc/llvm-project/r728584FDD0102CEF.html the class `SourceLocExpr` represents a function call to one of `__builtin_LINE()`, `__builtin_COLUMN()`, `__builtin_FUNCTION()`, `__builtin_FILE()`, or `__builtin_source_location()`.
Especially with the C++20 std::source_location it would be neat if cppinsights would support this.

Best regards!

**Comment by andreasfertig** [comment]
Hello @Ukilele,

thanks for bringing this up.

I don't understand what role `std::source_location` plays here. You're using the internals required to implement `source_location`; the STD type works fine as far as I know.

I'm a bit reluctant to implement this transformation. Getting the correct information from `SourceLocExpr` seems difficult, and I'm unsure about the benefit.

Andreas

**Comment by Ukilele** [comment]
Hi Andreas,
your welcome!

I just brought up `std::source_location` because this was the class I originally used when I came accross this issue. I guess that since it's standarized since C++20, its usage might be higher than the one of builtin compiler-intrinsics. For a simplification of the code to reproduce the issue, I switched to `__builtin_LINE()`.
When using `std::source_location::current()` you will get a similar output:
```c++
std::source_location::current(/* INSIGHTS-TODO: CodeGenerator.cpp:3851 stmt: SourceLocExpr */)
```
I agree that it definitely is no urgent or important issue.

**Comment by andreasfertig** [comment]
Hello @Ukilele,

usually I appreciate reduced issue reports, as I did here. Yet, your new `std::source_location::current()` reminded me of the implementation of `source_location`. Despite the standard not mentioning it, `current` takes a parameter of from `__builtin_source_location`. Looks like I have to act on this one :-)

Andreas

**Comment by Ukilele** [comment]
Awesome, that was quick :) Thanks a lot 👍
