### ISSUE TITLE
Using pointer to member as a template argument is converted to the type of the member

### ISSUE THREAD

**Issue by ninkibah** [andreasfertig/cppinsights#60]
I wrote some code that uses a pointer to a class member as a template parameter:

[pointerToMemberBug.cpp.txt](https://github.com/andreasfertig/cppinsights/files/2284383/pointerToMemberBug.cpp.txt)
Sadly, the expanded code is showing as:
#ifdef INSIGHTS_USE_TEMPLATE
template<>
struct Index<int> // instead of struct Index<&Person::age>

t always seems to use the type of the data member as the template type. For example, if I change Person::age to a long, then struct Index<long> is generated.

**Comment by andreasfertig** [comment]
Hello ninkibah,

it could be that the `auto` template parameter is the root of the problem. Maybe this is handled incorrectly. I will have a look into it. Thanks for reporting.

Just one question, the `template<> struct Index<XXXX>` is always generated, correct. It changes from `int` to `long` if you change the type of `Person::age`.

**Comment by ninkibah** [comment]
Andreas,
Yes the template<> struct Index<XXXX> is always generated, and the type of XXXX is always the type of Person::age.

BTW, is it at all possible to generate output, even when the code has errors? The reason I ask is, your tool would then become a major asset in developing template code.

**Comment by andreasfertig** [comment]
Code with errors in blocked in the web version. In general it does compile code with errors, but the result is questionable. After all it is a clang tool and with that has the same limits as a compiler. You can try it out locally and tell me what you think.

**Comment by ninkibah** [comment]
Andreas, this works wonderfully. Thank you.

**Comment by andreasfertig** [comment]
Hello ninkibah,

your welcome! And thanks for pointing out the error that I can improve the tool.
