### ISSUE TITLE
Superfluous parentheses in declarations are handled incorrectly

### ISSUE THREAD

**Issue by DivineWinds** [andreasfertig/cppinsights#606]
Input:
```
void (*p);
```
Output:
```
void (*) p;
```
This is wrong and fails to compile. Ideally the unnecessary parentheses would be removed but leaving them untouched is also an option.

**Comment by andreasfertig** [comment]
Hello @DivineWinds,

thanks for spotting this! A fix is on its way.

Andreas

**Comment by DivineWinds** [comment]
Thanks for the fix @andreasfertig. I'm sorry for being a nuisance but unfortunately I discovered a problem with it. `void (**p);` and deeper multilevel pointers still exhibit the old behaviour. Also, using cv-qualifiers breaks even the one level pointer case, that is, `void (*volatile p);` becomes `void (*pvolatile);` (I'm only using `volatile` to skip the initalizer. `const` does the same thing). Combining the two results in the old behaviour as well: `void (**volatile p);` becomes `void (**volatile) p;`.

**Comment by andreasfertig** [comment]
Hello @DivineWinds,

thanks for the testing. What is the use-case for all that? Is this production code?

Andreas

**Comment by DivineWinds** [comment]
I'm not aware of any use case. I originally found this by just copying the
Most Vexing Parse example from Wikipedia and changing the type of my_dbl to
double*. There was no reason for me to do this other than to see what would
happen. After you fixed that, I tried some more complicated cases just to
see how robust the fix was. So, as far as I know, you can ignore this issue
and no production code would be affected.

Στις Τρί 13 Φεβ 2024, 16:22 ο χρήστης Andreas Fertig <
***@***.***> έγραψε:
