### ISSUE TITLE
can not open "libxml2s.lib" ？？？ what is  "libxml2s.lib" ? from where?

### ISSUE THREAD

**Issue by Nu1i** [andreasfertig/cppinsights#638]

**Comment by andreasfertig** [comment]
Hello @Nu1i,

sorry, I need more context.

Andreas

**Comment by Nu1i** [comment]
> Hello @Nu1i,
> 
> sorry, I need more context.
> 
> Andreas

I use visual studio 2022 after cmake，it occured error when compile. the error message is "LNK1181	无法打开输入文件“libxml2s.lib”	insights" means can not open the libxml2.lib file. pls see the image
![image](https://github.com/andreasfertig/cppinsights/assets/38694534/8d935c1d-8968-4ffc-ac3a-dfd365509674)

**Comment by andreasfertig** [comment]
Hello @Nu1i,

Thanks! Unfortunately, I don't use Visual Studio or Windows in general. A quick search led me to this issue in Clang [55817](https://github.com/llvm/llvm-project/issues/55817). It looks like the issue could depend on the cmake or clang version.

Maybe the C++ Insights cmake file could do something. But at the moment, I don't see it as a C++ Insights issue. 

Andreas

**Comment by Nu1i** [comment]
> Hello @Nu1i,
> 
> Thanks! Unfortunately, I don't use Visual Studio or Windows in general. A quick search led me to this issue in Clang [55817](https://github.com/llvm/llvm-project/issues/55817). It looks like the issue could depend on the cmake or clang version.
> 
> Maybe the C++ Insights cmake file could do something. But at the moment, I don't see it as a C++ Insights issue. 
> 
> Andreas

thank you so much.
