### ISSUE TITLE
Lambda Capture by value for reference typed variables.

### ISSUE THREAD

**Issue by textshell** [andreasfertig/cppinsights#64]
According to http://eel.is/c++draft/expr.prim.lambda#capture-10 and cppreference.org lambdas seems to capture references as copies of the decayed type.

But cppinsights does not agree given:
```
#include <string>

void func(const std::string& arg) {
 
  [arg] {
    return arg.size();
  };
}

int main() {
  std::string b;
  
  func(b);
}
```

It generates:
```
    const std::basic_string<char, std::char_traits<char>, std::allocator<char> > & arg;
    
    public: __lambda_5_3(const std::basic_string<char, std::char_traits<char>, std::allocator<char> > & _arg)
    : arg{_arg}
    {}
```

Where i would expect based on the linked section that it would produce:
```
    const std::basic_string<char, std::char_traits<char>, std::allocator<char> > arg;
```

**Comment by andreasfertig** [comment]
Thanks for reporting that. Please check if it is correct now.

**Comment by textshell** [comment]
Thanks. Now output matches my expectations and a small test program also agrees that by value captures of references don't allow modifying the original object.
