### ISSUE TITLE
Lambda Capture Variable Not Used in Generated Code

### ISSUE THREAD

**Issue by glucu** [andreasfertig/cppinsights#640]
**Issue:**
The generated code for a lambda function that captures a variable by value does not use the captured variable in the lambda body. 

**Example Code:**
```cpp
int main()
{
    int z{5};
    auto sum = [z](int x, int y){ return x + y + z; };
}
```

**Generated Code**
```cpp
int main()
{
  int z = {5};
    
  class __lambda_7_16
  {
    public: 
    inline /*constexpr */ int operator()(int x, int y) const
    {
      return (x + y) + x;
    }
    
    private: 
    int z;
    
    public:
    __lambda_7_16(int & _z)
    : z{_z}
    {}
    
  };
  
  __lambda_7_16 sum = __lambda_7_16{z};
  return 0;
}
```

**Expected Generated Code**
```cpp
int main()
{
  int z = {5};
    
  class __lambda_7_16
  {
    public: 
    inline /*constexpr */ int operator()(int x, int y) const
    {
      return (x + y) + z; // Correct: `z` is used here 
    }
    
    private: 
    int z;
    
    public:
    __lambda_7_16(int & _z)
    : z{_z}
    {}
    
  };
  
  __lambda_7_16 sum = __lambda_7_16{z};
  return 0;
}
```

**Note**
The issue seems to be intermittent, and it may not reproduce consistently.

**Comment by andreasfertig** [comment]
Hello @glucu,

thanks for reporting this issue! After a couple of days and tries, I was not able to reproduce it. Are you running a self-build version?

Andreas

**Comment by glucu** [comment]
Hi @andreasfertig 

I also tested further and was unable to reproduce the problem. Odd. This was run on **cppinsights.io**.
