### ISSUE TITLE
[[likely]] and [[unlikely]] delete condition bodies

### ISSUE THREAD

**Issue by dvtate** [andreasfertig/cppinsights#644]
![Screenshot from 2024-06-13 16-23-38](https://github.com/andreasfertig/cppinsights/assets/15305612/63fe222b-bb82-41a7-8415-c00980195a82)

cppreference: https://en.cppreference.com/w/cpp/language/attributes/likely

**Comment by andreasfertig** [comment]
Hello @dvtate,

thanks for reporting this issue! A fix is on its way.

Andreas
