### ISSUE TITLE
Segmentation fault with `noexcept( condition )`

### ISSUE THREAD

**Issue by Ukilele** [andreasfertig/cppinsights#654]
Hey Andreas,
followin code:

```c++
template<bool B>
void f() noexcept(B)
{
}
```
leads to following console output:
```
insights: /github/workspace/cppinsights/InsightsHelpers.cpp:1503: bool clang::insights::EvaluateAsBoolenCondition(const clang::Expr&, const clang::Decl&): Assertion `res' failed.
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
Segmentation fault (core dumped)
```
The same output for C++11 until C++2c. No other transformations are enabled.

**Comment by andreasfertig** [comment]
Hello @Ukilele,

thanks for spotting this! That's from a recent change where I changed the `noexcept` conversion. I didn't consider the primary template. A fix is on its way.

Andreas

**Comment by Ukilele** [comment]
Yes, I spotted it while testing the new `Show noexcept internals` feature. Nice feature by the way :)
