### ISSUE TITLE
Incorrect type of a function returning a reference to an array

### ISSUE THREAD

**Issue by languagelawyer** [andreasfertig/cppinsights#74]
For the following code
```c++
int arr[5][3];

decltype(auto) f(int i)
{
    return arr[i];
}
```
Insight produces (array declaration is skipped)
```c++
int (&)[3] f(int i)
{
  return arr[i];
}
```
whilst it shall be
```c++
int (&f(int i))[3]
{
  return arr[i];
}
```

**Comment by andreasfertig** [comment]
Hello languagelawyer,

thanks for reporting that. I'll have a look into it for how to fix it.

**Comment by languagelawyer** [comment]
Prolly the easiest way to fix this is to use trailing return type.

**Comment by andreasfertig** [comment]
I just pushed a fix. Let me know what you think. It is without trailing return type and it passed all my existing tests.

**Comment by languagelawyer** [comment]
I've already tested it at the cppinsights.io
I've thought there is no easy way to put the function name into the correct place in such a function type with libclang, that is why I've proposed the use of trailing return type.
But it seems that it is not difficult, so there is no need in trailing return type.

**Comment by andreasfertig** [comment]
Yeah the way is ugly. I insert it in the string. But I used this system already.
At some point I think I will implement my own AST to type version. But so far I can life with libclang.
