### ISSUE TITLE
limits.h header isn't in include path

### ISSUE THREAD

**Issue by rayhamel** [andreasfertig/cppinsights#78]
If you include the standard C header `limits.h`, you get a `fatal error: 'limits.h' file not found`. The header `climits` is found, but since `climits` includes `limits.h`, compilation fails with the same error.

**Comment by andreasfertig** [comment]
Hello Ray,

I fix this issue. The following code works now: https://cppinsights.io/lnk?code=I2luY2x1ZGUgPGNzdGRpbz4KI2luY2x1ZGUgPGNsaW1pdHM+CgppbnQgbWFpbigpCnsKICAgIHJldHVybiBDSEFSX0JJVDsKfQ==&rev=1.0
