### ISSUE TITLE
Synchronize scrolling in the web version

### ISSUE THREAD

**Issue by pravic** [andreasfertig/cppinsights#8]
Hello,

First of all, thanks for this interesting and very useful tool. It will be really helpful for newcomers and those who want to refresh his knowledge of modern C++ standards.

Just a suggestion of a tiny UX improvement: it'd be nice to synchronize code output in the web page when scrolling. Right now you have to scroll both panels manually to compare output side by side.

Optionally, may be something similar to diff view with slightly colored lines (of course, a full diff highlighting, like in github, isn't needed).

**Comment by andreasfertig** [comment]
Hello pravic,

thank you!

I think it is hard to scroll both. Sometimes the transformed code is more than the original one. For example, if you play with templates and instantiate a lot of them the right side has way more content than the left. If you know a way to do that I welcome a PR.

Initially I had such a diff view in mind. I still do. Its just that my web development skills are, well low. CodeMirror does offer a diff plugin, so it is possible I think. PRs welcome applies here as well :-)

**Comment by pravic** [comment]
>  Sometimes the transformed code is more than the original one. 

That's the point :) It's called "Synchronized scrolling", a very popular feature in some code editors and in almost all diff viewers.

But yes, I think it is related to the diff feature itself which might be implemented in some JS component already. Who knows.

**Comment by nishanthkarthik** [comment]
@andreasfertig Can I pick this up?

**Comment by andreasfertig** [comment]
Hello @nishanthkarthik,

that would be great!

Andreas

**Comment by nishanthkarthik** [comment]
@andreasfertig The [merge view](https://codemirror.net/demo/merge.html) supports what we need. However, both editor instances are tied to a single `div`. Ideally, we should be able to control when we show the diff (say, when we get a response back from the server).

Is this behavior okay?

- When the user inputs code into the left pane for the first time, the diff view is off and the right pane is empty
- When the user compiles the code, the diff view is shown with the modified lines, highlighted
- When the user starts modifying the left pane again, the diff lines are not highlighted until the next time he clicks on compile

The alternative is to leave the highlighted lines on all the time, but I don't think that would be an intuitive experience. As the user modifies the left pane after compiling, both views are not in sync and a diff is no longer necessary.

What do you think?

**Comment by andreasfertig** [comment]
Hello @nishanthkarthik,

your approach sounds good to me. Don't worry about the `div`. It is the way it is for no specific reason.

Andreas

**Comment by nishanthkarthik** [comment]
I'm using `MergeView` to extract out an instance of `CodeMirror`.

```
function initMergeView() {
  return CodeMirror.MergeView(document.getElementById('merge-view'), {
    lineNumbers: true,
    origLeft: null,
    value: '',
    orig: '',
    mode: 'text/x-c++src',
    connect: 'align',
    allowEditingOriginals: false,
    showDifferences: false,
    collapseIdentical: false
  });
}

var cppMergeView = initMergeView();
var cppEditor = cppMergeView.editor();
```

`initMergeView` has to be called each time the code changes, judging from the [sample use here](https://codemirror.net/demo/merge.html). There is no direct member to manually edit the right pane's content. The only way is to reinitialize the `MergeView` every time.

**Comment by nishanthkarthik** [comment]
The merge view leaves a lot to be desired. It internally uses [diff-match-patch](https://github.com/google/diff-match-patch)

![Screenshot_2019-08-18_20-40-06](https://user-images.githubusercontent.com/7759435/63226544-7fb30680-c1f8-11e9-8934-fffdc64124f2.png)

**Comment by andreasfertig** [comment]
Hello @nishanthkarthik,

thanks for your work. I think it looks ok. 
One question I have is, how does it look in a bigger examples with multiple diffs? Can the colors of each block be defined? A real big example might be 
[#101](https://github.com/andreasfertig/cppinsights/blob/master/tests/Issue101.cpp) or [#188](https://github.com/andreasfertig/cppinsights/blob/master/tests/Issue188.cpp). There might be other examples in the test folder with lambdas which are also interesting. My fear is, that we end up with two yellow colored editors.

Another interesting case is something like [this](https://cppinsights.io/lnk?code=dm9pZCBGdW5jKGludCB4ID0gMykge30KCmludCBtYWluKCkKewogIEZ1bmMoKTsKfQ==&insightsOptions=cpp17&std=cpp17&rev=1.0):

```
void Func(int x = 3) {}

int main()
{
  Func();
}
```

There we have an inline diff.

Andreas

**Comment by nishanthkarthik** [comment]
Changing color is purely CSS. I think that should be okay.

I'll try out the large examples and post screenshots here.

I am also gonna try using monaco's diff view without using npm. The diff view will be similar to VS Code.

**Comment by andreasfertig** [comment]
Hello,

this issue has been open for quite a while now. I still believe that the diff is not easy to compare. I'll close the issue in a couple of days if nobody objects and shows some progress.

Andreas
